inputs/simple.json, inputs/simple_inner.json, osbs/api.py, osbs/build.py, osbs/cli/main.py, osbs/conf.py
Add `simple` build JSON. Make switching between build JSONs easier.
=> Build types

tests/__init__.py, tests/constants.py, tests/fake_api.py, tests/mock_jsons.sh, tests/mock_jsons/0.4.1/authorize.txt, tests/mock_jsons/0.4.1/build_put.json, tests/mock_jsons/0.4.1/build_test-build-123.json, tests/mock_jsons/0.4.1/builds_list.json, tests/mock_jsons/0.4.1/get_user.json, tests/unit_test.py
Fixes #4 
Can someone review briefly please?
CC @jpopelka @twaugh @mmilata
=> Create units tests with mocked responses for CI

osbs/http.py
With kerberos proxy, getting /oauth/authorize first returns 401
Unauthorized and then 302 with the token after providing kerberos
credentials. However the pycurl adapter returned headers for the first
(401) response where the Location header with the token was not present.
This fix makes it return headers for the last (302) response.
=> http: return headers for the last request

osbs/api.py, osbs/cli/main.py, osbs/conf.py, osbs/constants.py, osbs/core.py, osbs/http.py
review please
CC @mmilata @twaugh
=> Rewrite logs and wait

osbs/api.py, osbs/build.py, osbs/conf.py, osbs/core.py
=> build: enable configuring 'use_auth' of metadata plugin

osbs/cli/main.py
=> cli: new arg: --output={json,text}

osbs/http.py
Hopefully this increases the project's health according to Landscape.
=> Avoid access to protected class member.

README.md, docs/osbs_instance_setup.md
=> add deployment docs

osbs/http.py
This works on both Python 2 and 3.
Low priority.
=> Use email.parser.Parser() to parse HTTP headers

osbs.spec
This is pretty much the same as https://github.com/DBuildService/dock/commit/6c4d0421d7983aa677bcb0cd025a8781af8fd330 to keep things in good shape and consistent.
=> Better specfile

osbs/api.py, tests/fake_api.py, tests/unit_test.py
=> Fix get build logs

osbs/http.py, tests/mock_jsons/0.4.1/authorize.txt, tests/unit_test.py
@pbabinca this should resolve your issue
Unfortunately, it still doesn't work on py 3 (on my machine).
=> http: fix parsing headers on 2.7

osbs/api.py, osbs/cli/main.py, osbs/conf.py
=> Cli submit generic build

osbs/http.py, tests/httpbin_test.py
let's use httpbin.org
requests and urllib3 use it
Fixes #62
=> http: exercise osbs.http against real webserver

osbs/__init__.py, osbs/build/build_response.py, osbs/build/manipulate.py, osbs/build/spec.py, osbs/cli/main.py, osbs/conf.py, osbs/constants.py, osbs/core.py, osbs/exceptions.py, osbs/http.py, osbs/utils.py, tests/constants.py, tests/requirements.txt, tests/unit_test.py
Resolves #102
Closes #101
+ fix repositories in cli output (am lazy to open new PR)
+ display commit_id in cli output (more laziness)
=> fix curl multi and watch

osbs/core.py, osbs/exceptions.py
#107 + my fixup commit (github doesn't allow to push to `pr/%d` ref)
=> 107 updated

osbs/api.py, osbs/cli/main.py, osbs/core.py, osbs/http.py
=> api: make getting logs non-blocking

osbs/build/spec.py, tests/unit_test.py
=> validate build ID against upstream regex

inputs/simple_inner.json, osbs/build/build_request.py
Fixes #117 - can you please check if it really works? The ticket is a bit vague so I'm not sure if it fixes the right issue.
=> Change source registry for simple builds

inputs/prod-without-koji_inner.json, osbs/build/build_request.py, osbs/build/manipulate.py, tests/unit_test.py
=> prod: don't use koji when yum repo is specified

osbs/build/build_response.py
dock: https://github.com/DBuildService/dock/pull/127
Fixes #111
=> build response: add methods for retrieving tar metadata

osbs/cli/main.py
=> cli: let client accept yum repo urls

docs/osbs_instance_setup.md
=> Update setup docs for OpenShift 1.0

osbs/api.py, osbs/conf.py, tests/test_exceptions.py, tests/unit_test.py
Needed for DBuildService/atomic-reactor#197.
=> API fixes for atomic-reactor

osbs/build/build_request.py
This is used to construct unique tag for image.
@mmilata can you review and merge please?
=> secret build type: use unique image name

osbs/api.py, osbs/build/build_response.py, osbs/cli/main.py, osbs/constants.py, osbs/core.py
Fixes #144
OpenShift does the exact same thing.
=> new command: cancel build

osbs/http.py
Some places were missed by #68.
=> Exception reporting improvements in osbs.http

docs/configuration_file.md
=> docs: document configration file

docs/osbs_instance_setup.md
Fixes #157 
CC @maxamillion
@mmilata could you please take a look?
=> improve deployment guide

setup.py
Should have been done in the 'merge prod types' commit.
=> Don't try to install non-existent prod-with-secret files

osbs/build/spec.py, tests/unit_test.py
=> Reject URIs as values of registry_uri

inputs/prod_inner.json, inputs/simple_inner.json, osbs/build/build_request.py, tests/unit_test.py
Please do not merge until projectatomic/atomic-reactor#220 is merged and there was reasonable time to update buildroots to the new version.
=> Use the 'pull_base_image' plugin

osbs/build/build_request.py
Cosmetic change - not that creating new instances is wrong, I was just confused why each subclass creates new instance when we already have it as a member.
=> Use DockJsonManipulator member in BuildRequest subclasses

osbs/cli/main.py
=> cli: describe difference between --user and --username

inputs/prod_inner.json
Will move it to the enable-rebuild-triggers branch.
=> Temporarily disable import_image plugin

osbs/api.py, tests/unit_test.py
Previously, source_secret was mistakenly left out.
=> Set all build params for prod builds

docs/configuration_file.md, osbs/api.py, osbs/cli/main.py, osbs/conf.py, osbs/core.py, osbs/http.py
Do not merge yet, depends on #191.
Closes #160.
=> Implement authentication with client certificates

docs/configuration_file.md, osbs-client.spec, osbs/api.py, osbs/cli/main.py, osbs/conf.py, osbs/core.py, osbs/kerberos_ccache.py, tests/test_utils.py
Do not merge yet, depends on #191.
Creates (soft) dependency on [python-krbcontext](https://github.com/tkdchen/python-krbcontext) which we'll need to package.
=> Allow initalizing kerberos credentials from keytab

osbs/api.py, osbs/build/build_request.py, osbs/build/pod_response.py, osbs/build/spec.py, osbs/cli/capture.py, osbs/cli/main.py, osbs/conf.py, osbs/core.py, osbs/exceptions.py, osbs/kerberos_ccache.py, osbs/utils.py, tests/cli/test_capture.py
Includes fixes for:
* OSBS.update_labels_on_build() didn't return any value
* OSBS.create_image_stream() didn't use namespace argument
* CLI capture used wrong filenames
* bad openshift_required_version config would result in wrong error
=> Fixes for problems spotted by landscape.io

osbs/build/build_response.py, osbs/cli/main.py
New column names: base_image, base_image_id, and image_id.
=> Add support for showing layering metadata (fixes #254)

docs/configuration_file.md, docs/secret.md, inputs/prod_inner.json, osbs/api.py, osbs/build/build_request.py, osbs/build/spec.py, osbs/conf.py, tests/build/test_build_request.py
Depends on https://github.com/projectatomic/atomic-reactor/pull/282
=> Configure sendmail plugin

osbs/conf.py, tests/test_exceptions.py
\+ some general fixes
Fixes #263
=> conf: remove can_miss

inputs/prod_inner.json, inputs/simple_inner.json, osbs/build/build_request.py, tests/build/test_build_request.py
OSBS counterpart of projectatomic/atomic-reactor#349 (issue projectatomic/atomic-reactor#348).
=> Configure tag_and_push plugin

inputs/prod_inner.json, osbs/api.py, osbs/build/build_request.py, osbs/build/spec.py, osbs/conf.py
https://github.com/projectatomic/atomic-reactor/pull/344
=> Allow specifying build_json_dir for import_image plugin

inputs/simple_inner.json
The plugins were just missing in build json.
Closes #240.
=> Enable adding yum repos for simple builds

osbs-client.spec
=> spec: changes sugested in package review

inputs/prod_inner.json, osbs/build/build_request.py, tests/build/test_build_request.py
Depends on https://github.com/projectatomic/atomic-reactor/pull/319.
=> Configure koji_promote plugin

osbs/build/build_request.py
The `build_request.py` module has some pretty large `render()` methods. This pull requests breaks them up into manageable chunks so the overall process is easier to read and understand.
=> Reduce complexity in `osbs.build.build_request`

osbs/api.py, osbs/build/spec.py, osbs/cli/main.py, osbs/conf.py, tests/build/test_build_request.py
=> simple builds: enable setting image tag

osbs/build/build_request.py, osbs/conf.py, tests/build/test_build_request.py
=> Check that at least one registry is provided

osbs/api.py, osbs/build/build_request.py, osbs/build/spec.py, tests/build/test_build_request.py
=> Make setting architecture label optional

osbs/build/build_request.py, tests/build/test_build_request.py
Whenever OpenShift < 1.0.6 is used.
This is osbs counterpart of projectatomic/atomic-reactor#370.
=> Allow setting secret for pulp_sync in sourceSecret

docs/build_process.md
=> document parallel v1 & v2 workflow

docs/backups.md, osbs/api.py, osbs/cli/main.py, osbs/constants.py, osbs/core.py, osbs/utils.py, tests/fake_api.py, tests/test_api.py, tests/test_utils.py
Can be used for migrating OSBS instances.
Please test?
=> Add backup/restore functionality

osbs/api.py, osbs/core.py
Closes #216.
There's no timeout, we don't have it for any other watch methods either - should we?
=> Use watch API to wait for autoinstantiated builds

docs/examples.md
cc @maxamillion @mmilata @TomasTomecek
=> Add a couple of example configurations

osbs/core.py
To test: pause a builder and submit a job, then wait for an hour.
=> watch_resource: reconnect when connection closed (#339)

osbs/core.py
=> watch_resource: sleep 30s before reconnecting (#339)

osbs/cli/main.py
=> New --from-json parameter for list-builds (#351)

osbs/api.py, tests/test_api.py
This allows clients to work out what filename extension to expect for the 'docker save' output file.
=> New OSBS.get_compression_extension() method

osbs/api.py, osbs/cli/main.py, osbs/conf.py, osbs/core.py
Includes #375
* print-token-url: print an auth page url to get token
* get-serviceaccount-token: prints tokens set for serviceaccount
=> Two CLI options for oauth-enabled installations

osbs/api.py, osbs/cli/main.py, osbs/conf.py, osbs/core.py, tests/test_conf.py
The only functional change is to make sure osbs.conf-specific token (whether 'token' or 'token_file') can be overridden.
=> Tokens fixes

osbs/build/build_request.py, tests/build/test_build_request.py
See also https://github.com/projectatomic/atomic-reactor/pull/447
=> only set Build_Host label if specified in config

osbs/api.py, osbs/cli/main.py, osbs/core.py
* api
* cli
should I also add tests?
=> new call: "get-quota": get or list resource quota

osbs/api.py, osbs/build/build_request.py, osbs/build/spec.py, osbs/cli/main.py, osbs/conf.py, tests/build/test_build_request.py
See https://github.com/projectatomic/atomic-reactor/pull/461
=> Inject proxy in repos using 'proxy' config setting

osbs/utils.py
=> Use git reset --hard && git checkout

osbs/api.py, osbs/cli/main.py, osbs/constants.py, osbs/core.py
=> Add watch-builds command to track status change

osbs/build/build_request.py, tests/build/test_build_request.py
Requires https://github.com/projectatomic/atomic-reactor/pull/471; please do not merge before that PR.
=> Set koji_promote.target so the build gets tagged

osbs/core.py, tests/test_core.py
When the connection is closed, if the time since the last activity is less than a minute, finish.
Otherwise, ask again for logs starting from just after we last saw activity.
=> handle connection being closed while streaming logs

osbs/api.py, osbs/build/build_request.py, osbs/build/manipulate.py, osbs/cli/main.py, osbs/conf.py, osbs/utils.py
See my fork's page at https://www.quantifiedcode.com/app/project/bd1a52c2e00c4cff90df9252c23a1328/
=> Fix several small problems found by quantifiedcode.com

inputs/prod_inner.json, osbs/build/build_request.py, tests/build/test_build_request.py
Requires corresponding release of atomic-reactor with changes from: https://github.com/projectatomic/atomic-reactor/pull/493
=> Add build custom base image functionality

osbs/api.py, osbs/build/build_request.py, osbs/build/spec.py, osbs/cli/main.py, osbs/conf.py, tests/build/test_build_request.py, tests/build/test_spec.py, tests/test_conf.py
Overlapping commit from #422 needed to avoid unit testing conflicts. Merging this will also merge #422 .
=> Labels parameter

inputs/prod_inner.json, osbs/build/build_request.py, tests/build/test_build_request.py
Corresponding atomic-reactor changes:
https://github.com/projectatomic/atomic-reactor/pull/514
https://github.com/projectatomic/atomic-reactor/pull/516
These changes have been successfully tested with a repository containing a Dockerfile without a release label specified.
=> Configure bump_release plugin

inputs/prod_inner.json, osbs/build/build_request.py, tests/build/test_build_request.py
Corresponding atomic reactor PR: https://github.com/projectatomic/atomic-reactor/pull/525
=> Add support for name and version to bump release

osbs/api.py, osbs/cli/main.py, osbs/conf.py, osbs/utils.py, tests/test_api.py, tests/test_conf.py, tests/test_utils.py
Resolves: #393
Early preview, needs unit testing.
=> Add login subcommand

docs/configuration_file.md, inputs/prod_customize.json, osbs/build/build_request.py, osbs/build/manipulate.py, osbs/constants.py, tests/build/test_build_request.py
Signed-off-by: Adam Miller <maxamillion@fedoraproject.org>
=> first pass at enabling site-customizations

osbs/cli/main.py
osbs issue #485 
adds version option for osbs client
=> add --version option

inputs/prod_inner.json, osbs/build/build_request.py, osbs/build/manipulate.py, tests/build/test_build_request.py
=> Set osbs-client version in the build json

inputs/prod_inner.json, osbs/build/build_request.py, tests/build/test_build_request.py
Needs to be done after https://github.com/projectatomic/atomic-reactor/pull/603
=> Render plugin update_parent_image_stream_tag

inputs/prod_inner.json
Related: https://github.com/projectatomic/atomic-reactor/pull/613
=> Enable add_help plugin

inputs/prod_inner.json, tests/mock_jsons/0.5.4/build_test-build-123.json, tests/mock_jsons/0.5.4/build_test-build-cancel-123_get.json, tests/mock_jsons/0.5.4/build_test-build-cancel-123_put.json, tests/mock_jsons/0.5.4/builds_list.json, tests/mock_jsons/0.5.4/created_build_config_test-build-config-123.json, tests/mock_jsons/0.5.4/instantiated_test-build-config-123.json, tests/mock_jsons/0.5.4/pods.json, tests/mock_jsons/0.5.4/watch_build_test-build-123.json, tests/mock_jsons/1.0.4/build_test-build-123.json, tests/mock_jsons/1.0.4/build_test-build-cancel-123_get.json, tests/mock_jsons/1.0.4/build_test-build-cancel-123_put.json, tests/mock_jsons/1.0.4/builds_list.json, tests/mock_jsons/1.0.4/created_build_config_test-build-config-123.json, tests/mock_jsons/1.0.4/instantiated_test-build-config-123.json, tests/mock_jsons/1.0.4/pods.json, tests/mock_jsons/1.0.4/watch_build_test-build-123.json
is required for https://github.com/projectatomic/atomic-reactor/issues/475
=> remove plugins

osbs/api.py, osbs/utils.py, tests/test_utils.py
#499, creates label class for use across whole osbs
=> unified labels names

inputs/prod_inner.json, osbs/api.py, osbs/build/build_request.py, tests/build/test_build_request.py, tests/test_api.py
=> Create parent's ImageStreamTag

osbs/utils.py, tests/test_utils.py
When creating a BuildConfig name avoid underscores, which are not allowed at all, and periods, which are only allowed when followed by certain characters.
=> Avoid invalid BuildConfig names

docs/configuration_file.md
This was missed from https://github.com/projectatomic/osbs-client/pull/523 by mistake.
=> Describe new client_config_secret and token_secrets options

osbs/build/build_request.py, tests/build_/test_build_request.py
=> if build_image is used, it is also passed to worker build

docs/configuration_file.md, osbs/api.py, osbs/conf.py, tests/fake_api.py, tests/test_api.py
=> can_orchestrate option in config

docs/configuration_file.md
=> add orcherstrator and worker jsons into doc

osbs/core.py, tests/test_core.py
We retry up to 10 times, with a delay of 500ms between attempts.
This is necessary because OpenShift itself may be updating the Build object as well.
=> Retry on conflict updating labels/annotations

inputs/prod_inner.json, inputs/worker_inner:1.json, osbs/build/build_request.py, tests/build_/test_build_request.py
=> render koji_tag_build plugin

osbs/core.py
=> Log all attempts to update OpenShift objects

osbs-client.spec, setup.py
=> Fix spec typo and remove pytest-runner from setup.py

osbs-client.spec, osbs/__init__.py, setup.py
=> bump release and make it dev

osbs/api.py, osbs/cli/main.py, tests/test_api.py
=> LDAP auth method support

osbs/api.py
=> LDAP auth method, cosmetic changes

osbs/build/build_request.py, tests/build_/test_build_request.py
=> Disable pulp_pull when pulp is not used

docs/configuration_file.md, osbs/api.py, osbs/build/build_request.py, osbs/build/spec.py, osbs/conf.py, tests/build_/test_build_request.py
=> URL to info page as docker label

docs/configuration_file.md, inputs/prod_inner.json, inputs/worker_inner:1.json, osbs/api.py, osbs/build/build_request.py, osbs/build/spec.py, osbs/conf.py, tests/build_/test_build_request.py, tests/test_conf.py
=> Render fetch_maven_artifacts plugin

docs/configuration_file.md, osbs/api.py, osbs/conf.py, tests/test_api.py
=> Set a custom nodeselector for scratch builds if low_priority_node_selector config param is set

osbs/build/spec.py, tests/build_/test_build_request.py
=> disable specifying build_imagestream and build_image

.flake8
=> Add .flake8 so that Stickler CI know about our settings

osbs/cli/main.py
=> arrangement-version argument for worker build

osbs/cli/main.py, tests/test_api.py
=> arrangement-version argument for worker build fix

osbs/http.py, tests/test_http.py
=> iter_lines: set chunk_size = 1 so it would not wait for buffer to fill in

osbs/http.py
=> HttpStream safe__del__

osbs/build/spec.py
=> random seed before every random

osbs/core.py, osbs/http.py, tests/test_core.py, tests/test_http.py
=> http: remove decoded_json after python-requests merge

osbs/build/build_request.py, osbs/core.py, tests/fake_api.py, tests/test_cli.py, tests/test_core.py, tests/test_http.py
=> Remove unused imports

osbs/cli/main.py
=> allow source-registry-uri to be set from CLI

osbs/conf.py
=> Use a raw string when creating a regular expression

osbs/build/build_request.py, tests/build_/test_build_request.py
Signed-off-by: Bret Fontecchio <bfontecc@redhat.com>
=> Allow empty triggers in prod json

osbs/core.py, tests/constants.py, tests/fake_api.py, tests/mock_jsons/0.5.4/imagestream.json, tests/mock_jsons/1.0.4/imagestream.json, tests/test_core.py
=> import_image should return always true, regardless if tags changed

osbs/core.py, tests/test_core.py
=> don't log ERROR when checking for istreams and istags

osbs/api.py, osbs/build/build_request.py, osbs/build/spec.py, tests/test_api.py
=> branch name is always required

osbs/build/build_request.py, tests/build_/test_build_request.py
Signed-off-by: Bret Fontecchio <bfontecc@redhat.com>
=> Handle Null case for triggers in prod JSON

osbs/build/build_request.py, tests/build_/test_build_request.py
=> pass equal_labels configuration to worker

osbs/utils.py, tests/test_utils.py
Remove ImageChange triggers if triggers are removed from prod.json
=> Trigger remove2

inputs/config_map.json, osbs/api.py, osbs/build/config_map_response.py, osbs/core.py, tests/fake_api.py, tests/mock_jsons/0.5.4/create_config_map.json, tests/mock_jsons/1.0.4/create_config_map.json, tests/test_api.py
Add support for adding, getting, and deleting configMaps.
=> support configMaps

docs/testing.md
=> Add documentation about mock_jsons

inputs/orchestrator_inner:1.json
=> Run add_labels_in_dockerfile after bump_release

osbs/build/build_response.py, tests/build_/test_build_response.py
Signed-off-by: Adam Miller <maxamillion@fedoraproject.org>
=> add is_cancelled() to build_response.py

osbs/build/build_request.py
=> Update docstring for adjust_for_scratch

osbs/build/build_request.py, tests/build_/test_build_request.py
add render_koji_upload to build_request.
=> koji_upload: add to render in build_request

osbs/cli/main.py, tests/test_api.py
=> Export koji_upload_dir param to CLI

osbs/cli/main.py, osbs/utils.py
This adds two separate switches for osbs-client: one would skip
resourcequotas to pause/restore builder - and the other one would
continue if one of the resources has failed to be backed up
=> Allow skipping errors when builder is being backed up / restored

osbs/build/build_request.py, tests/build_/test_build_request.py
=> pass artifacts_allowed_domains to workers

osbs/build/pod_response.py, tests/build_/test_pod_response.py
=> New PodResponse.get_failure_reason() method

osbs/build/build_request.py, osbs/build/spec.py, tests/build_/test_build_request.py
=> Build request: pass yum_proxy value to workers

osbs/build/pod_response.py
=> pep8 N806 fixes (lowercase function variable names)

tests/build_/test_arrangements.py
Because the point of the test_arrangement.py tests is to verify the renderer changes are correct, and it knows where the templates are, it can also check whether there are missing tests.
Additionally, it can also catch the case where the default arrangement version has been incremented but there is no testing for the new arrangement.
=> Additional arrangement testing

inputs/orchestrator_inner:2.json, inputs/prod_inner.json, osbs/build/build_request.py, tests/build_/test_arrangements.py, tests/build_/test_build_request.py
=> enable and render koji_parent plugin

tests/build_/test_arrangements.py, tests/fake_api.py
=> Test more plugins in arrangements

tests/build_/test_arrangements.py
List prepublish_plugins before postbuild_plugins, since that is the order they run in.
Remove unnecessary code.
=> Some small tidy-ups

osbs/build/build_request.py, tests/build_/test_build_request.py
=> Also check release label aliases for autorebuild

inputs/prod_inner.json, inputs/worker_inner:1.json, inputs/worker_inner:2.json, inputs/worker_inner:3.json
This is needed since this atomic-reactor change:
https://github.com/projectatomic/atomic-reactor/pull/740
=> Set pulp_pull's insecure parameter

docs/development-setup.md
Here are some improvements to development-setup.md based on what I had to do to get prod and orchestrated builds working locally.
Perhaps it's better to just point people to osbs-box than to have development-setup.md, but as long as there is a development-setup.md, hopefully these changes are useful!
=> Development setup improvements

inputs/orchestrator_inner:4.json, inputs/worker_inner:4.json, tests/build_/test_arrangements.py, tests/fake_api.py, tests/test_api.py
=> Add new arrangement 4

osbs/api.py, osbs/build/build_request.py, tests/build_/test_build_request.py, tests/constants.py, tests/test_api.py
=> Remove platform from scratch build name

docs/configuration_file.md, inputs/orchestrator.json, inputs/orchestrator_inner:3.json, inputs/orchestrator_inner:4.json, osbs/api.py, osbs/build/build_request.py, osbs/conf.py, tests/build_/test_arrangements.py, tests/build_/test_build_request.py, tests/test_api.py, tests/test_conf.py
=> Build type nodeselectors for worker builds

inputs/orchestrator_inner:4.json, inputs/worker_inner:4.json, osbs/api.py, osbs/build/build_request.py, osbs/build/spec.py, osbs/cli/main.py, tests/build_/test_arrangements.py, tests/build_/test_build_request.py, tests/test_api.py
=> Enable inject_parent_image plugin

osbs/build/build_request.py, tests/build_/test_build_request.py
=> remove trigger plugins, for scratch builds

osbs/api.py, osbs/cli/main.py, tests/test_api.py
Let release value through (at least at this level).
=> Release value

osbs/api.py, tests/mock_jsons/0.5.4/build_test-orchestrator-build-123_logs.txt, tests/mock_jsons/1.0.4/build_test-orchestrator-build-123_logs.txt, tests/test_api.py
=> Fixes for get_orchestrator_build_logs

.stickler.yml
=> Configure Stickler-CI

osbs/build/build_request.py, osbs/repo_utils.py, tests/build_/test_build_request.py, tests/test_api.py
some minor errors have crept in and need to be removed. No functional
changes.
=> janitor: clean up some flake8 warnings

osbs/api.py, osbs/build/build_request.py, osbs/cli/main.py, osbs/constants.py, osbs/core.py, osbs/exceptions.py, osbs/utils.py, tests/build_/test_build_request.py, tests/constants.py, tests/fake_api.py, tests/test_api.py, tests/test_utils.py
Allow for isolated build type.
In accordance with:
http://osbs.readthedocs.io/en/latest/isolated_builds.html
=> Isolated Build Type

osbs/build/build_request.py, tests/build_/test_build_request.py
Related to https://github.com/projectatomic/atomic-reactor/pull/806
=> build_request: set expect_v2schema2 param for pulp_pull based on prefer_schema1_digest setting

osbs/build/build_request.py, tests/build_/test_arrangements.py
=> Set buildstep_logs parameter for koji_upload

osbs/build/build_request.py, tests/build_/test_arrangements.py
=> koji_upload takes platform parameter instead of buildstep_logs

osbs/constants.py, tests/build_/test_arrangements.py, tests/build_/test_build_request.py, tests/test_api.py
set DEFAULT_ARRANGEMENT_VERSION to 4 and adjust some test cases to
account for it.
=> arrangement 4: make arrangement 4 the default

inputs/orchestrator_inner:4.json, osbs/build/build_request.py, tests/build_/test_arrangements.py
Enable the compare_components plugin for version 4.
=> Add support for compare_components

osbs/repo_utils.py, tests/test_repo_utils.py
=> Allow dots in additional-tags

osbs/build/build_request.py, tests/build_/test_build_request.py
=> Fix flatpak build check in bump_release renderer

inputs/orchestrator_inner:4.json, osbs/build/build_request.py, tests/build_/test_arrangements.py
might be merged after this is merged https://github.com/projectatomic/atomic-reactor/pull/831
=> new remove worker metadata plugin

osbs/constants.py, osbs/http.py, tests/test_http.py
=> timeout for requests

inputs/prod_inner.json
=> extra.docker.config section missing in metadata for prod builds

osbs/api.py, osbs/constants.py, osbs/core.py, osbs/utils.py, tests/test_api.py, tests/test_core.py
=> updating BuildConfig retry

docs/build_process.md, docs/configuration_file.md, osbs/api.py, osbs/build/build_request.py, osbs/build/spec.py, osbs/conf.py, tests/build_/test_build_request.py
See https://github.com/projectatomic/atomic-reactor/pull/856
=> Remove references to NFS plugin

test.sh
```
sudo sh test.sh -x -s -k 'test_create_prod_build'
```
=> test.sh: the script parameters should be passed to py.test:

docs/configuration_file.md, osbs/build/build_request.py, osbs/conf.py, tests/build_/test_build_request.py, tests/test_conf.py
=> nodelesector for isolated build_type

osbs/api.py
=> isolated nodeselector fix

osbs/build/build_request.py, tests/build_/test_build_request.py
=> don't run import_image for scratch build

osbs/api.py, osbs/build/spec.py, osbs/cli/main.py, tests/build_/test_spec.py, tests/test_api.py
=> odcs parameters signing_intent and compose_ids

osbs/api.py, osbs/build/build_request.py, osbs/build/spec.py, osbs/conf.py, tests/build_/test_build_request.py
=> Add SSL auth support for ODCS in resolve_composes

docs/configuration_file.md
=> Clarify docs for odcs_* configuration parameters

osbs/api.py, osbs/build/build_request.py, tests/build_/test_build_request.py, tests/test_api.py
=> allow more isolated builds with different release

osbs/build/build_request.py, tests/build_/test_build_request.py
=> remove resolve_compose plugin if yum_repourls is used

osbs/api.py, tests/test_api.py
=> remove unused and deprecated API entry points

inputs/orchestrator.json, inputs/orchestrator_inner:5.json, tests/build_/test_arrangements.py
Enable autorebuild by adding ImageChange trigger and activating import_image plugin.
=> Enable rebuild triggers

osbs/api.py, tests/test_api.py
Signed-off-by: Chandrakant Kumar <k.03chandra@gmail.com>
=> Check logs is not None before performing string operation

osbs/api.py, tests/test_api.py
=> Fail if image name begins with component containing '.'

docs/configuration_file.md, osbs/api.py, osbs/build/build_request.py, osbs/build/spec.py, osbs/conf.py, tests/build_/test_build_request.py
=> support for reactor_config_map

osbs/api.py, osbs/build/build_response.py, osbs/cli/main.py, tests/build_/test_build_response.py, tests/test_api.py
=> removal of unused annotations

docs/configuration_file.md, osbs/api.py, osbs/build/spec.py, osbs/cli/main.py, osbs/conf.py, osbs/constants.py, tests/build_/test_build_request.py, tests/build_/test_spec.py, tests/fake_api.py, tests/test_api.py
=> unify build_image and build_imagestream by build_from

inputs/orchestrator_inner:5.json, osbs/build/build_request.py, tests/build_/test_arrangements.py
=> import_image will be as well exit plugin

osbs/build/build_request.py, tests/build_/test_arrangements.py
=> remove exit plugin image_image for scratch build

inputs/orchestrator_inner:5.json
=> import image exit isn't required

osbs/repo_utils.py
Signed-off-by: David Becvarik <dbecvari@redhat.com>
=> fixed typo in log message

osbs/api.py, osbs/build/build_request.py, osbs/build/spec.py, tests/build_/test_build_request.py
=> reactor config env for worker builds

osbs/build/config_map_response.py, tests/mock_jsons/0.5.4/create_config_map.json, tests/mock_jsons/1.0.4/create_config_map.json, tests/test_api.py
=> get_data_by_key recognizes yaml content

osbs/build/build_request.py, tests/build_/test_build_request.py
=> goarch param for orchestrator

inputs/orchestrator_inner:6.json, osbs/api.py, osbs/build/plugins_configuration.py, osbs/cli/main.py, tests/build_/test_arrangements.py, tests/build_/test_plugins_configuration.py, tests/test_api.py
koji_import gets rendered properly
platforms is an optional argument in arrangement6 and create_orchestrate_build shouldn't raise an error if it is omitted.
=> more platform 6 fixes

osbs/core.py, tests/test_core.py
=> Retry ensure_image_stream_tag() on conflict (OSBS-5369)

osbs/api.py, osbs/build/build_request.py, osbs/build/build_requestv2.py, tests/test_api.py
=> BuildRequestV2 should get outer template as param

osbs/build/build_requestv2.py, osbs/build/plugins_configuration.py, osbs/build/user_params.py, tests/build_/test_plugins_configuration.py, tests/build_/test_user_params.py
=> fix additional tags in arrangement 6

inputs/worker_inner:6.json
=> load_exported_image for pulp_push in arrangement 6

osbs/core.py, tests/test_core.py
core: don't loop forever waiting for a response
watch_resource() has an infinite loop until success or a bad http response.
If a valid http response is returned, but the response returns an empty
iterator, watch_resource will loop forever.
Change it to be a bounded loop that will return to wait() in 5 minutes. wait()
will then raise an error that is caught by wait_for_build_to_finish() or
wait_for_build_to_get_scheduled().
The current total timeout is 12 hours - 144 retries in wait_for_build_*, each
of which takes 5 minutes.
=> core: don't loop forever waiting for a response

.travis.yml
=> Run Travis CI push-triggered tests only on master branch

osbs/http.py, tests/test_http.py
=> HttpStream: don't raise exception on empty response

test.sh
Have this reuse an existing container that's been stopped.
Also make it easy to mount more volumes into the test container.
Generate HTML coverage report.
=> test.sh: add resurrection, EXTRA_MOUNT, htmlcov

osbs/api.py, osbs/constants.py, tests/test_api.py
=> raise error if release label contains forbidden characters

osbs/api.py, osbs/core.py, tests/test_api.py, tests/test_core.py
=> import image imports only specified tags, if provided

osbs/cli/main.py
=> Allow import of specific image tags from CLI

osbs/api.py, tests/test_api.py
OpenShift allows multiple builds on the same BuildConfig at the same
time, with only one running and the others queued to run when a build
completes. As such, osbs-client should not raise an error if another
build of the same BuildConfig is active.
Rename _verify_no_running_builds to _verify_running_builds and do not
raise an error if a build is running. Do log an info message of the
names of builds currently running, to make it easier to detect runaway
build processes and other issues that might cause one BuildConfig to
be repeatedly and unnecessarily built.
=> api: allow multiple running builds of the same BuildConfig

osbs/core.py, tests/test_core.py
raise exceptions if no filter match is found and there's only
one response, or if there's no filter key and only one response.
=> better error handling for get_build_config_by_labels_filtered

CONTRIBUTING.md
=> Update CONTRIBUTING.md to refer to the review checklist

docs/configuration_file.md, osbs/build/plugins_configuration.py
Couple of tiny cleanups as a result of https://github.com/projectatomic/atomic-reactor/pull/1064 and https://github.com/projectatomic/atomic-reactor/pull/1065.
=> Flatpak config cleanups

osbs/api.py, tests/fake_api.py, tests/mock_jsons/1.0.4/builds_list_empty.json, tests/mock_jsons/1.0.4/builds_list_one.json, tests/test_api.py
=> use build for koji id, if already exists

osbs/build/plugins_configuration.py, tests/build_/test_plugins_configuration.py
See https://github.com/projectatomic/atomic-reactor/pull/1093 for reference
=> Set koji_target for add_filesystem plugin

osbs-client.spec, test.sh
=> Don't install py3 deps for py2 testing

.pylintrc, .travis.yml, osbs/build/spec.py, osbs/build/user_params.py, osbs/cli/main.py, test.sh, tests/build_/test_arrangements.py
=> Enable pylint analysis

osbs/api.py, tests/test_api.py
=> Deprecation warning: arrangement_version <= 5

osbs/core.py, tests/test_core.py
Since watch_resources operates in a loop, a single bad response
from the _get call shouldn't cancel operation.  Instead, catch
the exception from check_response() and increment a counter.
Only raise the exception to the next level if there are multiple
bad responses in a single watch_resources call.
=> core.py: tolerate bad response in watch_resources

README.md
=> README.md: discuss CLI access a little more

osbs/core.py
=> change note in stream_logs about which errors are silenced

osbs-client.spec, setup.py
=> Do not package customization files

osbs/build/plugins_configuration.py, osbs/build/user_params.py, tests/build_/test_plugins_configuration.py, tests/build_/test_user_params.py
=> Run resolve compose plugin even when yum repourl are provided

osbs/core.py
This debug line may leak OCP oauth secrets
=> Remove forgotten debug

inputs/worker_inner:6.json, tests/build_/test_arrangements.py
=> Add hide files plugin

osbs/build/plugins_configuration.py, tests/build_/test_plugins_configuration.py
=> floating tags

osbs/exceptions.py, osbs/repo_utils.py, tests/test_api.py, tests/test_repo_utils.py
=> Use str() to report ScannerError

osbs/api.py, osbs/cli/main.py, tests/build_/test_arrangements.py, tests/test_api.py
=> Disallow usage of prod builds and arrangements <= 5

docs/build_process.md, docs/configuration_file.md, docs/examples.md, osbs/conf.py, tests/build_/test_arrangements.py, tests/build_/test_build_request.py, tests/test_conf.py
* OSBS-6665
https://github.com/projectatomic/osbs-docs/pull/76
=> Remove v1 content building support

inputs/orchestrator_inner:6.json, tests/build_/test_arrangements.py
* OSBS-7542
Part of https://github.com/containerbuildsystem/atomic-reactor/pull/1227
=> Enable OMPS integration plugins

.travis.yml, osbs-client.spec
=> enable fedora 30 testing and disable 28, py3 only for rhel8 & fedora

tests/requirements.txt, tests/test_api.py
See https://github.com/containerbuildsystem/atomic-reactor/pull/1255
=> Fix tests for pytest version 5

osbs/core.py
=> Use repr to log JSON response content

osbs/api.py, tests/test_api.py
name and component needs to have explicit value,
version, release may be using env variable
* OSBS-7697
=> more stricter required labels checking,

osbs/api.py, osbs/build/build_requestv2.py, osbs/cli/main.py, tests/test_api.py
=> Skip build option, to update just buildconfig for autorebuilds

osbs/api.py
=> pass is_autorebuild to update_build_config_with_trigger to change label

osbs/api.py, osbs/build/build_requestv2.py, tests/build_/test_build_requestv2.py, tests/test_api.py
=> new triggered_after_koji_task parameter

inputs/orchestrator_inner:6.json, osbs/build/build_requestv2.py, osbs/build/plugins_configuration.py, osbs/build/user_params.py, tests/build_/test_arrangements.py, tests/build_/test_plugins_configuration.py, tests/build_/test_user_params.py
=> run new koji_delegate prebuild plugin

inputs/orchestrator_sources_inner:6.json, osbs/api.py, osbs/build/build_requestv2.py, osbs/cli/main.py, osbs/constants.py, tests/test_api.py
=> Source containers API

.travis.yml, osbs/api.py, osbs/build/plugins_configuration.py, osbs/build/user_params.py, osbs/constants.py, tests/build_/test_plugins_configuration.py
The same as #898 I had to just force travis to run build
=> Source render plugin configuration

osbs/api.py, osbs/cli/main.py, tests/test_api.py
=> required component for source container builds

inputs/orchestrator_sources_inner:6.json, osbs/api.py, osbs/build/build_requestv2.py, osbs/build/plugins_configuration.py, tests/build_/test_build_requestv2.py
`tag_and_push` requires `fetch_sources` plugin
=> Source containers: fetch_sources & tag_and_push plugin

osbs/cli/main.py
=> CLI: Add --signing-intent option

osbs/build/plugins_configuration.py
=> don't run compress, koji_tag plugins for scratch source builds

osbs/api.py, osbs/core.py, osbs/utils.py, tests/test_api.py
=> imagestreamtag race

inputs/orchestrator_sources_inner:6.json
=> Run store_metadata plugin for source containers

osbs/api.py, osbs/constants.py, osbs/utils.py, tests/test_api.py
=> allow enable autorebuilds with skip-build for non-existent tag

inputs/orchestrator_inner:6.json, inputs/worker_inner:6.json, tests/build_/test_arrangements.py
=> Run remote source plugins

osbs/core.py, osbs/utils.py, tests/test_core.py
Fixes OSBS-8448
import_image_tags is encountering 504 errors on RHEL7 because urllib3 isn't retrying them properly. add a new retry_on_gateway_timeout function and wrap _check_import_image_response in it.
Also, unify some of the associated handling of _check_image_image_response and rename it
_get_import_image_response_tags
=> core: make import_image_tags handle 504 errors

osbs/cli/main.py
=> return different return value than 0 when build fails

.pylintrc, .travis.yml, osbs/exceptions.py, test.sh, tests/test_api.py
=> Change tests and travis for correct working with Fedora 31

osbs/exceptions.py, osbs/utils.py, tests/test_utils.py
*OSBS-8552
Added new exception for better understanding,
changed error message by adding information about branch,
changed tests for correct working.
Signed-off-by: Salatskyi Serhii <ssalatsk@redhat.com>
=> Improve "cannot find commit" error message

setup.py
=> Make sure json schemas are installed by setup.py

.mdlint_style, .mdlrc, .travis.yml, CONTRIBUTING.md, README.md, docs/backups.md, docs/build_process.md, docs/configuration_file.md, docs/development-setup.md, docs/examples.md, docs/osbs_instance_setup.md, docs/pull_request_template.md, docs/resource.md, docs/secret.md, docs/testing.md, test.sh
- [n/a] Code coverage from testing does not decrease and new code is covered
- [n/a] Pull request includes link to an osbs-docs PR for user documentation updates
=> Lint all Markdown files and enable CI MD lint

osbs/utils/yaml.py, tests/utils/test_yaml.py
=> Better schema validation failure reporting

docs/build_process.md, osbs/build/plugins_configuration.py, tests/build_/test_arrangements.py, tests/build_/test_plugins_configuration.py
=> Plugins decide for themselves whether to run (osbs-client doesn't)

inputs/worker_inner:6.json, tests/build_/test_arrangements.py
=> Embed content sets information in built container images

osbs/utils/yaml.py, tests/utils/test_yaml.py
=> Better validation errors reporting

osbs/utils/__init__.py, tests/utils/test_utils.py
=> move ImageName from atomic-reactor to osbs-client

osbs/build/build_requestv2.py, tests/build_/test_build_requestv2.py
* CLOUDBLD-1228
Add variables to buildconfig, let openshift propagate them into
buildroot.
=> Propagate build_env variables from config map

osbs/api.py, osbs/build/build_requestv2.py, osbs/build/user_params.py, osbs/cli/main.py, osbs/core.py, osbs/utils/__init__.py, tests/build_/test_arrangements.py, tests/build_/test_build_requestv2.py, tests/test_api.py, tests/test_core.py, tests/utils/test_utils.py
=> create imagestreams with registry name

osbs/repo_utils.py
=> Deprecate additional-tags file

osbs/build/build_requestv2.py
=> convert ':' to '-' in imagestream and imagestream tag names

osbs/schemas/container.json
=> allow modular_koji_tags to be boolean in schema

osbs/api.py, osbs/build/build_requestv2.py, osbs/build/plugins_configuration.py, osbs/build/user_params.py, osbs/build/user_params_meta.py, tests/build_/test_arrangements.py, tests/build_/test_build_requestv2.py, tests/build_/test_plugins_configuration.py, tests/build_/test_user_params.py, tests/build_/test_user_params_meta.py, tests/test_api.py
=> Refactor user params

osbs/api.py, osbs/constants.py, tests/test_api.py
=> Dashes should not be allowed in version tag

osbs/http.py, tests/test_http.py
Log response text from OCP
Added hook to requests to log response when a HTTP request failed.
However with retries it's tricky, if failure limit is reached, it will
just fail withou passing response to hooks. To be able to process
request while using retries, Retry(raise_on_status=False) has to be
used.
However this param is available from urllib3 > 1.15, in RHEL7 there is
urllib3 ~= 1.10, so response text will be logged only with newer urllib3
version.
<s>Also Retry() rasises exception by default when a HTTP request was not
successful. To keep this behavior and not break current code, another
hook has been added to raise exception when request was not successful.</s>
(no need for this, code checks responses and this change would even break unittests)
* CLOUDBLD-2800
Signed-off-by: Martin …
=> Log HTTP error responses

osbs/api.py, tests/test_api.py
=> check if imagestreamtag exists for manual build when autorebuilds are enabled

.github/workflows/unittests.yaml, osbs/build/build_requestv2.py, test.sh, tests/build_/test_build_requestv2.py
=> Fix source container deadline

osbs/constants.py, osbs/repo_utils.py, test.sh, tests/test_repo_utils.py
=> Fail build if container or content_sets file have unexpected extension

osbs/build/build_requestv2.py, tests/build_/test_build_requestv2.py
=> set cpu and memory requests for source container from reactor config map

osbs/__init__.py, osbs/constants.py, osbs/utils/__init__.py, tests/utils/test_utils.py
*CLOUDBLD-4640
Signed-off-by: Serhii Salatskyi <ssalatsk@redhat.com>
=> Complete loggers by new level and message handler for user warnings

osbs/schemas/container.json
=> Update schema to allow remote_sources in container.yaml

osbs/schemas/container.json, tests/utils/test_yaml.py
=> Fix remote_sources jsonschema

osbs/schemas/container.json
=> Remove build methods from container.json

tests/build_/test_plugins_configuration.py, tests/test_core.py, tests/utils/test_utils.py
Ports #1037 + fixes additional issue not present in master branch
=> [OCP3] Fix new flake8 issues

.pylintrc, osbs/core.py, osbs/osbs_http.py, osbs/tekton.py, tests/conftest.py, tests/test_api.py, tests/test_core.py, tests/test_http.py, tests/test_retries.py
=> Add methods for pipeline manipulation

.github/workflows/unittests.yaml
=> fix coveralls run issue

osbs/api.py, osbs/cli/main.py, osbs/cli/render.py, osbs/tekton.py, tests/test_api.py, tests/test_tekton.py
=> add osbsapi methods for koji-c

tests/test_api.py
=> fix test_get_build_labels

osbs/build/user_params.py, tests/build_/test_user_params.py, tests/test_api.py
=> Add namespace user param

osbs/build/user_params.py, osbs/cli/main.py, tests/build_/test_user_params.py
=> add userdata cli option and add it to user params

osbs/api.py, tests/test_api.py
=> fix get_build_name method

osbs/cli/main.py, osbs/tekton.py, tests/cli/test_main.py, tests/test_tekton.py
non-existing keys, also cancel pipeline run if get_logs fails
* CLOUDBLD-8220
=> pipeline run get error message, should be more careful about reading

osbs-client.spec, osbs/tekton.py
=> print pipeline run info when pipeline run doesn't finish successfully

osbs/tekton.py, osbs/utils/__init__.py, tests/test_tekton.py, tests/utils/test_utils.py
=> sanitize pipeline run label values for openshift

osbs/tekton.py, tests/test_tekton.py
aren't updated properly sometimes
* CLOUDBLD-8615
=> add more debugging for update_labels, so we can find out why labels

osbs/utils/__init__.py
Signed-off-by: Chenxiong Qi <cqi@redhat.com>
- [n/a] Code coverage from testing does not decrease and new code is covered
=> Restore image name conventions document

osbs/api.py, osbs/tekton.py, tests/test_api.py, tests/test_tekton.py
This was replaced by tekton results
CLOUDBLD-9046
=> Remove support for openshift labels

docs/configuration_file.md, docs/development-setup.md
=> remove clusters and can_orchestrate occurrences

osbs/cli/main.py, osbs/conf.py, osbs/tekton.py, tests/test_conf.py, tests/test_tekton.py
=> remove pipeline runs after once the build is finished

osbs/tekton.py, tests/test_tekton.py
=> Fix delay in log retrieval

osbs/tekton.py, tests/test_tekton.py
=> Fix log messages in tekton module

osbs/tekton.py, tests/test_tekton.py
=> rotate fetching logs

osbs/api.py, osbs/cli/main.py, osbs/tekton.py, tests/cli/test_main.py, tests/test_api.py, tests/test_tekton.py
exit task results
* CLOUDBLD-10949
=> remove annotation code for pipeline run, and use plugin results from

osbs/api.py, osbs/tekton.py, tests/test_api.py
=> new get_task_results api method

osbs/cli/main.py, osbs/tekton.py, tests/test_tekton.py
=> handle cases in tekton module when tekton object is removed during run

osbs/tekton.py, tests/test_tekton.py
=> report task error message when there is ocp issue

osbs/tekton.py, tests/test_tekton.py
=> report task error message if no errors were found in steps

osbs/tekton.py, tests/test_api.py, tests/test_tekton.py
=> fix final platforms
