- .travis.yml
By adding `sudo: false` to the `.travis.yml` file we can speed up the CI tests by having Travis CI run them in docker containers rather than VMs.
> Enable docker container architecture for Travis CI.

- tests/unit_test.py
Here's an extension of one of the existing test cases to check that the `Architecture`, `Vendor`, `Build_Host`, and `Authoritative_Registry` labels will be set via the prebuild plugin.
It doesn't test loading those values from config, only the translation from build request keywords into build JSON.
> Test build JSON for implicit labels.

- osbs/http.py
Sometimes OpenShift self-signed certificate isn't created correctly and
CommonName is 127.0.0.1 instead of IP address/FQDN under which is
OpenShift available. This change allows ignore this inconsistency which
would otherwise cause following fatal error:
>    SSL: certificate subject name (127.0.0.1) does not match target host
>    name 'openshift.example.com'
> http: Don't verify host if verify_ssl is disabled

- osbs/api.py
- osbs/core.py
- osbs/exceptions.py
- osbs/http.py
New exceptions module with base OsbsException class and two
exceptions derived from it:
* OsbsResponseException, for OpenShift 'fail' responses
* OsbsNetworkException, for (possibly transient) network
failures
The OsbsResponseException is thrown by the api and core modules
when they see a fail HTTP response.
The PycurlAdapter class catches exceptions thrown during
request handling and maps them to either OsbsNetworkException
or OsbsException as appropriate.
This fixes #43.
> More coherent exception handling

- .landscape.yml
Fixes #53 
This enables [pep8](https://www.python.org/dev/peps/pep-0008/). I would really like if our code could be pep8 compliant. Especially when you can enable pep8 in you text editors/IDEs. What do you think?
> add landscape.io config

- inputs/prod-without-koji_inner.json
- inputs/prod_inner.json
- osbs/api.py
- osbs/build/build_request.py
- osbs/build/manipulate.py
- osbs/build/spec.py
- osbs/cli/main.py
- tests/unit_test.py
This adds support for configuring the [new `add_yum_repo_by_url` plugin in dock](https://github.com/DBuildService/dock/pull/78).
* Configuration for plugin in prod_inner.json.
* Keyword argument for OSBS.create_build, `yum_repourls`.
* ProductionBuild fills in configuration (if present) from
keyword argument.
* Test case for the above.
* New CLI argument for build, `--add-yum-repo URI`.
> Configure add_yum_repo_by_url plugin

- osbs/http.py
This was causing failures with Python 3.
> Decode HTTP headers from ISO-8859-1 before using split() on them

- osbs/api.py
- osbs/exceptions.py
Converting all exceptions to OsbsException can lose information about the context of the original exception. It would be nice to be able to show that context.
This happens implicitly with Python 3, but to aid reporting with Python 2 we can do it explicitly.
This is only activated in Python 2, by detecting whether the `__context__` attribute is set.
Before:
```
Traceback (most recent call last):
File "/usr/bin/osbs", line 9, in <module>
load_entry_point('osbs==0.4', 'console_scripts', 'osbs')()
File "build/bdist.linux-x86_64/egg/osbs/cli/main.py", line 311, in main
File "build/bdist.linux-x86_64/egg/osbs/cli/main.py", line 153, in cmd_build_logs
File "build/bdist.linux-x86_64/egg/osbs/api.py", line 33, in catch_exceptions
osbs.exceptions.OsbsException: TypeError("'Response' object has no …
```
> Explicit exception chaining and enhanced reporting.

- tests/unit_test.py
We know that this test fails with Python 3, and issue #74 is open to track that. How about skipping it on Python 3 until it's important enough to fix?
> Skip failing Python 3 test

- osbs/api.py
Could do with more mock JSON responses for better test coverage, especially errored/cancelled builds.
From line note in #66: https://github.com/DBuildService/osbs/pull/66/files#r30439416
> OSBS.get_build_logs(): use BuildResponse for state parsing

- tests/fake_api.py
- tests/unit_test.py
Here are some tests for the `osbs.api.OSBS` class. It calls most of the methods and largely checks their return value types.
Still missing:
* `create_prod_build()`
* `create_prod_without_koji_build()`
* `create_simple_build()`
* `create_build()`
* `create_build_from_buildrequest()`
* `wait_for_build_to_finish()`
> Tests for osbs.api.OSBS class

- osbs/build/build_request.py
Before this change following exception was raised:
File ".../osbs/osbs/build/build_request.py", line 88, in template
path, repr(ex))
TypeError('not enough arguments for format string',)
For a reference I've called osbs with following commands:
```
echo -e "\n[default]\nsources_command=\nvendor=\nbuild_host=\nauthoritative_registry=\n" > /tmp/osbs.conf
osbs --verbose --config /tmp/osbs.conf --openshift-uri http://127.0.0.1:9443 --registry-uri 127.0.0.1:5000 build -u pbabinca --arch x86_64 --git-commit master -g 'git+http://github.com/TomasTomecek/docker-hello-world' -c docker-hello-world --build-type prod-without-koji --build-json-dir /nonexistent
```
> Pass two arguments to string used in OsbsException

- osbs/http.py
2.6 doesn't have keyword arguments therefore it fails with:
TypeError('decode() takes no keyword arguments',)
Fixes #86
> http: string decoding, py 2.{6,7} compat

- osbs/http.py
Fixes #94
pycurl on rhel 6 is raising pycurl.E_CALL_MULTI_PERFORM multiple times;
not sure why
@pbabinca
> http: resolve odd behavior on rhel 6

- osbs/api.py
- osbs/build/build_response.py
- osbs/cli/main.py
- osbs/core.py
- osbs/http.py
- osbs/utils.py
- tests/unit_test.py
Fixes #90
This patch also introduces more methods for BuildResponse object so we
don't need to traverse in build json.
Also did some cleanup in
* wait_for_build_to_*
* cli/main.py
If anyone could review, please.
@pbabinca @twaugh
> API CHANGE: all api calls return BuildResponse

- osbs/http.py
let's ignore it and hope for the best
Fixes #97
> http: pycurl on rhel 6 frequently raises E_CALL_MULTI_PERFORM

- osbs/build/build_response.py
I use it together with method is_running() to find out if OpenShift will
do something with the build or I can proceed with getting the
build and/or buildlogs.
> New method for BuildResponse() object: is_pending()

- osbs/core.py
Not only useful for actually see what is that log record but I use it to
match and filter out the log records.
> Prefix debug logging of response.content with a description

- docs/secret.md
- inputs/prod-with-secret.json
- inputs/prod-with-secret_inner.json
- osbs/api.py
- osbs/build/build_request.py
- osbs/build/spec.py
- osbs/cli/main.py
- osbs/conf.py
- osbs/constants.py
- tests/unit_test.py
This provides support for builds that require a secret, such as a key or certificate, as part of their workflow.
It assumes the OpenShift 'Secret'-type resource has already been created, and simply sets the `sourceSecret` resource name as directed.
> Support for custom builds with source secrets

- osbs/api.py
- osbs/build/build_request.py
- osbs/build/spec.py
The simple build type ignored the value of metadata_plugin_use_auth even
though it has the store_metadata_in_osv3 plugin enabled.
Related to #41 and DBuildService/dock#134.
The other option is to remove *store_metadata_in_osv3* from the simple build json. I don't know if we want to have the plugin there or not.
> simple build: use metadata_plugin_use_auth option

- osbs/exceptions.py
- osbs/http.py
Fixes #136.
Now the output is:
```
Traceback (most recent call last):
File "/usr/bin/osbs", line 9, in <module>
load_entry_point('osbs==0.13.1', 'console_scripts', 'osbs')()
File "build/bdist.linux-x86_64/egg/osbs/cli/main.py", line 319, in main
File "build/bdist.linux-x86_64/egg/osbs/cli/main.py", line 130, in cmd_build
File "build/bdist.linux-x86_64/egg/osbs/api.py", line 28, in catch_exceptions
File "build/bdist.linux-x86_64/egg/osbs/api.py", line 232, in create_build
File "build/bdist.linux-x86_64/egg/osbs/api.py", line 28, in catch_exceptions
File "build/bdist.linux-x86_64/egg/osbs/api.py", line 168, in create_prod_with_secret_build
File "build/bdist.linux-x86_64/egg/osbs/build/build_response.py", line 37, in json
File "build/bdist.linux-x86_64/egg/osbs/http.py", line 156, in json …
```
> Better reporting for HTTP errors (#136)

- osbs/cli/main.py
> Specify namespace when following logs for created build (#138)

- docs/resource.md
- osbs/api.py
- osbs/build/build_request.py
- osbs/cli/main.py
- osbs/conf.py
To set resource quota, use `osc create -f quota.yaml` on a file like this:
```yaml
apiVersion: v1
kind: ResourceQuota
metadata:
name: quota
spec:
hard:
pods: 10
cpu: "2"
memory: 2Gi
storage: 20Gi
```
Now `osc describe quota myquota` will show the used and total amount of each resource type.
You can set default per-build limits either by setting them in the OSBS build configuration file (`cpu_limit`, `memory_limit`, `storage_limit`), or by setting defaults that OpenShift will apply to builds that do not specify their limits:
```yaml
apiVersion: v1
kind: LimitRange
metadata:
name: limits
spec:
limits:
- default:
cpu: 100m
memory: 512Mi
storage: 2Gi
type: Container
```
You can set per-build limits using the `--cpu-limit`, `--memory-limit`, and `--storage-limit` OSBS command line options.
You …
> Set resource limits for builds if specified (#85)

- osbs/http.py
Until now error message wasn't very useful even with verbose = True:
File ".../osbs/osbs/api.py", line 28, in catch_exceptions
return func(*args, **kwargs)
File ".../osbs/osbs/api.py", line 74, in list_builds
serialized_response = response.json()
File ".../osbs/osbs/http.py", line 157, in json
self._check_status_code()
File ".../osbs/osbs/http.py", line 184, in _check_status_code
raise HTTPError(url, self.status_code, message, None, None)
HTTPError()
Full output with this change:
$ osbs --without-auth list-builds
2015-06-09 21:31:56,805 - osbs - DEBUG - Logging level set to debug
* Adding handle: conn: 0x1234b80
* Adding handle: send: 0
* Adding handle: recv: 0
* Curl_addHandleToPipeline: length: 1
* - Conn 0 (0x1234b80) send_pipe: 1, recv_pipe: 0
* About to connect() to …
> Print http body if check_status_code raised HTTPError

- docs/secret.md
Since OpenShift 0.6.1 we can create secrets using `oc secrets new`, which is easier than constructing JSON.
Document this.
> docs/secrets.md: describe `oc secrets new`

- osbs/core.py
`Openshift.create_build()` needs the JSON, not the internal representation of it.
> Openshift.start_build(): give correct argument to create_build()

- osbs/build/build_response.py
- osbs/cli/main.py
For identical functionality use get_build_name() method.
> BuildResponse: build_id property is unused

- osbs/api.py
- osbs/cli/main.py
- osbs/constants.py
- osbs/core.py
This new API method tells OpenShift to fetch new ImageStream tags for a repo being tracked in an external registry.
> New API method import_image()

- inputs/prod_inner.json
- inputs/simple_inner.json
- osbs/build/build_request.py
- tests/unit_test.py
With this change, any local `osbs.conf` referencing JSON files that still list these plugins as post-build plugins should still continue to work.
> Name exit plugins as exit plugins (fixes #171)

- osbs/cli/main.py
- tests/unit_test.py
```
main.py: error: invalid choice: 'asd' (choose from u'list-builds', u'watch-build', u'get-build', u'cancel-build', u'import-image', u'get-token', u'get-user', u'build-logs', u'build')
```
> cli,help: get rid of 'u' prefix in help

- inputs/prod.json
- inputs/simple.json
- osbs/build/build_request.py
- tests/unit_test.py
This is for several reasons:
* currently Origin does not understand triggers from named ImageStreamTags
* additional plugins will need to be enabled for rebuild functionality
* the triggering ImageStreamTag is not set correctly at the moment (#192)
Note that `CommonBuild.render()` has been changed so that it only sets the trigger From field if there is a trigger to set, and condition should remain even when triggers are enabled as some BuildConfigs will be created without triggers.
> Temporarily disable build triggers

- inputs/prod_inner.json
As a side effect, this would mean that the image copied to NFS would also be gzipped (previously it wasn't compressed at all). I'm not sure if this is desirable. I can turn this off by running the `compress` plugin after the uncompressed squashed image gets copied to NFS. @pbabinca @twaugh @TomasTomecek any ideas if this is ok or if it should be switched back?
> Use compress plugin in prod, change load_squashed_image to load_exported_image

- inputs/prod_inner.json
- inputs/simple_inner.json
- osbs/api.py
- osbs/build/build_request.py
- osbs/build/spec.py
- osbs/utils.py
- tests/constants.py
- tests/fake_api.py
- tests/test_utils.py
- tests/unit_test.py
This PR makes sure we get three things right:
- `imagestream` argument for `ImportImagePlugin`
- `docker_image_repo` argument for `ImportImagePlugin`
- name of trigger that built image depends on
Also, the second commit fixes minor issue, where openshift url for `check_and_set_rebuild` wasn't previously substituted in `BuildRequest`.
> Imagestream naming

- inputs/prod_inner.json
without this, it doesn't log anything
> set logger of pulp plugin to INFO

- inputs/prod_inner.json
- osbs/build/build_request.py
- tests/unit_test.py
This pull request is for adding the `check_and_set_rebuild` and `import_image` plugins only if at least one trigger is specified. It also adds a test case so we can test both with-triggers and without-triggers.
> Enable rebuild-related plugins only if there are triggers

- tests/fake_api.py
- tests/unit_test.py
The URL to response map has been moved into the `Connection` object, as well as the custom callbacks referenced by it and the lookup function, `get_definition_for()`.
This lookup function now also returns the key in the response map, allowing a custom callback to modify the response for that URL the next time it is requested.
This work prepares the way for https://github.com/projectatomic/osbs-client/pull/202.
> Fake API: framework changes to allow responses to change over time

- osbs/build/build_request.py
- osbs/build/spec.py
- osbs/utils.py
- tests/constants.py
- tests/test_utils.py
- tests/unit_test.py
Some `FROM` directives may want to specify a particular version of an image, i.e. the part after ':' in the tag name. To accommodate this, the BuildConfig names need to be more specific -- to allow more than one branch to have triggers at a time -- and the ImageStreamTag names used in triggers need to include the whole tag name (still excluding the registry part).
Fixes #217.
> Set correct BuildConfig names and imageChange ImageStreamTags

- osbs/cli/main.py
- osbs/core.py
- osbs/exceptions.py
- osbs/http.py
- tests/fake_api.py
- tests/httpbin_test.py
- tests/unit_test.py
Blocking and streaming http responses now live in a separate classes.  The blocking response is implemented using the streaming response. Each streaming response has its own curl and curl_multi handle.
The streaming response has to be explicitly closed. The preferred way is to use it as a context manager which ensures that it is closed when exception is raised in the middle of reading the stream. Because it doesn't fit into our current API, the class also tries to free the curl resources when it finishes reading the http stream and also when it's gargabe collected.
> Refactor http module

- osbs/build/build_request.py
Let's allow users to pull from any registry they will specify in dockerfile.
> simple: don't pull image from provided registry, let users decide

- osbs/exceptions.py
- osbs/utils.py
Otherwise we just get `CalledProcessError` with no information.
> Report exceptions when dealing with git

- osbs/conf.py
- tests/test_exceptions.py
So we don't have
```
2015-07-30 11:24:20,991 - osbs - ERROR - Configuration error: Specified section 'default' not found in '/etc/osbs.conf'
```
all over the place
> read config lazily

- osbs/api.py
- tests/build/test_build_request.py
One of the tests was missing an `assert` statement, and `OSBS.create_build_from_buildrequest()` didn't work at all.
> Random one-line fixes for small bugs

- osbs/core.py
- osbs/utils.py
- tests/test_utils.py
This pull request has fixes for two bugs which combined to cause #241. I was testing against Origin 1.0.5, which perhaps has stricter validation that earlier releases.
The first issue is that we were not checking whether a PUT request for an updated BuildConfig was successful.
The second issue is that `get_imagestreamtag_from_image()` could return an ImageStream-format name (e.g. 'fedora') instead of an ImageStreamTag (eg. 'fedora:latest').
The second issue became apparent once the first was fixed:
```
osbs.exceptions.OsbsResponseException: {
"kind": "Status",
"apiVersion": "v1",
"metadata": {},
"status": "Failure",
"message": "BuildConfig \"docker-hello-world-fedora\" is invalid: triggers[0].from.name: invalid value 'fedora', Details: ImageStreamTag object references must be in the form …
```
> Fixes for updating BuildConfig

- docs/configuration_file.md
- osbs/api.py
- osbs/conf.py
- osbs/constants.py
- osbs/core.py
- osbs/http.py
This allows authentication to OpenShift from within the build pod, by looking for the `/var/run/secrets/kubernetes.io/serviceaccount` path and using it if available.
It only does so if `use_auth` is not set to `False` and no other authentication credentials have been supplied.
This behaviour can be explicitly enabled or disabled by setting `builder_use_auth = false` in the configuration file.
Why might you explicitly enable it? For instance, if the only authorized users use client certificates (so `use_auth` must be off), the plugins will need to authenticate and the only way they can do so is by enabling `builder_use_auth`.
Why might you explicitly disable it? For instance, if the osbs-client version installed in the buildroot image is older than this pull request merge, plugins will not …
> Use service account token inside build pod

- osbs/api.py
- osbs/build/__init__.py
- osbs/build/pod_response.py
- osbs/cli/main.py
- osbs/conf.py
- osbs/core.py
- tests/fake_api.py
- tests/mock_jsons/0.5.4/pods.json
- tests/mock_jsons/1.0.4/pods.json
- tests/test_api.py
- tests/test_core.py
Querying pods requires a different API endpoint as it is a Kubernetes API rather than specifically Origin, so I've added a new `Openshift` constructor parameter to allow for that.
There is a new `PodResponse` class, which `OSBS.get_pods_for_build()` returns a list of (cf. `list_builds`).
I've added a test case for it, which required some mock JSON. To fetch that, I also added a command line verb for it as well... which ironically has decreased overall test coverage.
> New API method get_pod_for_build() (fixes #238)

- docs/configuration_file.md
- docs/secret.md
- inputs/prod.json
- osbs/api.py
- osbs/build/build_request.py
- osbs/build/spec.py
- osbs/conf.py
- osbs/constants.py
- tests/build/test_build_request.py
- tests/fake_api.py
- tests/test_api.py
New configuration parameter `openshift_required_version`.
When this is 1.0.6 or later, use the `secrets` array to give pulp its secret.
Otherwise, use the `sourceSecret`.
Rename `source_secret` build parameter to `pulp_secret` but retain compatibility.
> Use secrets array with Origin 1.0.6 (fixes #234)

- osbs/build/build_response.py
- osbs/utils.py
- tests/test_utils.py
Let's at least spell RFC3339 correctly even if we can't get it working for any timezone but UTC (https://github.com/projectatomic/osbs-client/pull/232).
> Spell RFC3339 correctly

- osbs/build/build_request.py
- osbs/conf.py
- tests/build/test_build_request.py
- tests/test_api.py
The reason for this PR is to demonstrate a fix for the problem identified in https://github.com/projectatomic/osbs-client/pull/250#discussion_r40073359.
Does it make sense to do it this way?
> Use pkg_resources.parse_version() for handling version numbers

- .travis.yml
- MANIFEST.in
- osbs-client.spec
- osbs/utils.py
- requirements-py3.txt
- setup.py
- tests/test_utils.py
Provides robustness against changes in timestamp format.
Unfortunately I couldn't find a way to get this working with Python 2.6.
> Use dateutil to parse ISO8601 timestamps with Python 3

- osbs/cli/capture.py
Here are some fixes for using the `--capture` option.
`response.json()` can raise a status exception, but the calling code won't be expecting it. Instead, decode the JSON from the content directly.
For Kubernetes endpoints, the API begins differently ("api" instead of "oapi"). Trim the beginning of those URLs as well as OpenShift ones.
> Capture fixes

- osbs/cli/render.py
- osbs/utils.py
* get rid of .PIPE -- why pipe, when no one reads it?
* since git removes empty dir if clone fails (which ends up as OSError
from shutil.rmtree), we should clone inside a new dir in temp
directory
> utils: improve checkout_git_repo

- osbs/build/build_response.py
- osbs/cli/main.py
Related to projectatomic/atomic-reactor#339 / projectatomic/atomic-reactor#352.
Simply returns the list of the JSON objects, like the other methods that return pieces of `BuildResponse`. I can rework it to return list of actual python object that can e.g. return the string that can be used to docker-pull the image by its digest, if desired.
> Extract v2 digests from BuildResponse

- inputs/prod_inner.json
- osbs/build/build_request.py
- tests/build/test_build_request.py
If we are using v1 we want to use `pulp_push`, otherwise we want `pulp_sync`. Only one of those plugins should be enabled, not both.
> Configure pulp_sync plugin

- osbs-client.spec
> spec: require python-argparse on rhel6

- osbs-client.spec
- tests/test_http.py
- tests/test_utils.py
Looks like I turned Python3 builds off in 93d5854 (don't ask me why) and nobody has objected so far.
Let's turn them on again.
It'd also be nice to run tests when building the packages, so here's a `%check` section.
There are however some packages (e.g. `flexmock`) missing on `rhel`/`epel` so we can run the tests on Fedora only.
We also have to skip (if there's no internet connection) tests that try to access `httpbin.org`, because there's no connection in `koji` build environment. Here's example scratch-build [build.log](https://kojipkgs.fedoraproject.org//work/tasks/7898/11717898/build.log)
> Add %check section and build also for Python3

- osbs/build/spec.py
- tests/build/test_spec.py
The '/v2' suffix was not being taken into account correctly because the regular expression for stripping off the scheme from the URI was also stripping off the resource.
> Fix registry URI version parsing

- osbs/api.py
- osbs/build/build_request.py
- osbs/build/spec.py
- osbs/utils.py
- tests/build/test_build_request.py
- tests/test_api.py
The `git_push_url` configuration parameter and `git_branch` parameter to `create_prod_build()` are now both optional.
If either is omitted, rebuild triggers are disabled.
> Make git_branch and git_push_url optional

- osbs/build/build_request.py
- osbs/build/spec.py
- osbs/utils.py
- tests/build/test_build_request.py
- tests/build/test_spec.py
Pulp requires the scheme part of the docker registry URI, and so `pulp_sync` needs to be configured with it.
Don't strip out the scheme part when creating build parameters.
Strip out the scheme part for the source registry URI.
Strip out the scheme part for `tag_and_push` configuration.
Strip out the scheme part for `spec.output.to.name`.
> pulp_sync requires scheme part of docker registry URI

- osbs/build/build_request.py
- tests/build/test_build_request.py
Partially reverts 36e1bef6c85f685484cc1c07db524555bebfc528. Related to #266.
When new labels were used with old a-r the result was mix of old (provided by a-r/Dockerfile) and new (provided by osbs-client) labels.
During the migration to the new set, we should:
- use the old set in osbs-client
- use the alias feature of atomic-reactor to add new-style alias for the
old label.
> Revert implicit labels to the old standard

- osbs/build/build_request.py
- osbs/build/spec.py
- tests/build/test_build_request.py
We no longer require a secure registry when creating ImageStreams.
Requires https://github.com/projectatomic/atomic-reactor/pull/386.
> Configure import_image's insecure_registry parameter

- docker-compose.yml
- osbs/cli/main.py
- osbs/utils.py
- tests/test_utils.py
Previously:
```
jboss-kieserver-6-docker-20151130-050421                        | complete | user1/jboss-kieserver-6-docker:this-target-name-is-so-long-it-cant-fit-anywhere-docker-candidate-20151130050421
jboss-decisionserver-6-docker-20151130-054836                   | complete | user1/jboss-decisionserver-6-docker:this-target-name-is-so-long-it-cant-fit-anywhere-docker-candidate-20151130054836
openshift-enterprise-node-docker-20151130-115732                | complete | user2/openshift-enterprise-node-docker:long-target-name-docker-candidate-20151130115732
```
Now:
```
jboss-eap-6-docker-20151130-041010                                                 | complete                    | jboss-eap-6/eap64-openshift:0.0-0
jboss-kieserver-6-docker-20151130-050421 …
```
> cli: shorten output of list-builds

- osbs/core.py
- tests/fake_api.py
- tests/test_api.py
Using auth on python 3 resulted in OsbsException: KeyError(b'access_token',)
Essentially reverts f7aafa6 since the headers are unicode/str after the http refactoring in 61f327b.
> Fix authentication for Python 3

- tests/test_utils.py
Some of the `pytest` expectations were failing because of extra keyword arguments.
> Fix kerberos_ccache test cases

- osbs/api.py
- osbs/build/build_response.py
- osbs/core.py
Fixes a bug where two builds were started the first time we created a BuildConfig.
Another thing we could do is to have single argument constructor where the code would detect `HttpResponse`s and automagically call `.json()` on them. I slightly prefer doing it explicitly.
> BuildResponse: only accept JSON in constructor

- docs/secret.md
The github docs referenced in this link lands on a 404. Updating to new kubernetes project docs.
> update secrets doc with new k8s docs link

- osbs-client.spec
If there isn't conditional on the Requires for python2 vs python3 version of the backend libs then we are left with a dangling symlink:
```
Last metadata expiration check performed 0:20:51 ago on Mon Jan  4 17:12:33 2016.
Dependencies resolved.
=======================================================================================================================
Package                        Arch          Version                          Repository                         Size
=======================================================================================================================
Installing:
krb5-workstation               x86_64        1.14-12.fc24                     rawhide                           860 k
osbs-client                    noarch …
```
> osbs-client Require python3-osbs-client when py3 or broken symlink is installed

- osbs/api.py
- tests/test_api.py
Shouldn't need to provide git_branch=None or target=None.
> OSBS.create_build(): increase API compatibility

- osbs/api.py
- osbs/cli/main.py
- osbs/conf.py
- osbs/core.py
- osbs/utils.py
- tests/test_api.py
Passing it as a parameter everywhere clutters the code and serves no
purpose. It is initialized in OSBS constructor and lives as a property of
class Openshift now.
Breaks our Python API in case non-default namespace is used.
Closes #333.
---
* I took the liberty of removing support for listing builds in all namespaces. It wasn't working for some time now. I can make it work if anybody thinks it's useful.
* The `osbsapi` decorator checks if the methods are called with `namespace` kwarg and prints warning if it's the case. This means that we don't break compatibility with API users that use the default namespace. With little bit more work we can probably unbreak it for API users that use other namespace, though I don't think there are any.
* If this PR is merged I'll fix the osbs-client …
> Refactor: don't pass namespace as an argument

- osbs/api.py
- osbs/cli/main.py
- osbs/core.py
Previously, all builds were fetched and then each build's status was examined.
Now, the fieldSelector is set to match status=running in the builds query when the --running option is passed to the CLI tool. This means only running builds will be returned.
API changes:
- OSBS.list_builds() now accepts a 'field_selector' keyword argument
This also brings us closer to an implementation for #252.
> Improve performance for `list-builds --running`

- osbs/utils.py
This replaces
```
osbs.build.spec - DEBUG - registry_uris = '[<osbs.utils.RegistryURI object at 0x7f64c8a44dd0>]'
```
in debug output with proper registry URIs
> utils: show URI as a repr for RegistryURI

- osbs/api.py
- osbs/cli/main.py
- osbs/utils.py
This should solve #342. I'm wondering if the `resume-builds` subcommand should also take the resource quota as a parameter to facilitate resuming builds after interrupted backup command?
> Different resource quota name for backup pause

- osbs/http.py
This allows the connection to end normally when closed by the server.
> HttpStream: don't raise for E_PARTIAL_FILE

- inputs/prod.json
- inputs/simple.json
- osbs/api.py
- osbs/build/build_request.py
- osbs/build/spec.py
- osbs/cli/main.py
- osbs/conf.py
- osbs/constants.py
- tests/build/test_build_request.py
Closes #356.
I'm not quite sure where to put the default value, whether into *spec.py*, *conf.py*, or both.
> Make it possible to specify buildroot to be used

- osbs/cli/main.py
Since args override configuration file values, setting a default value for an argument will always mask the configuration file value.
> Don't set arg defaults for config items

- docs/configuration_file.md
- osbs/api.py
- osbs/build/build_request.py
- osbs/build/spec.py
- osbs/conf.py
- tests/build/test_build_request.py
@maxamillion tested this and it seems to work: http://koji.stg.fedoraproject.org/koji/getfile?taskID=90071405&name=build.log (the auth, at least)
> Configurable secret for koji ssl certs

- osbs/api.py
- tests/test_api.py
This removes the build_image keyword argument from the create_build API, and instead gets it from configuration/CLI.
> We should use build_image from config rather than create_build kwarg

- osbs/build/build_request.py
- tests/build/test_build_request.py
We will always use the'save' tarball, even for v2-only builds.
> Run compress plugin even for v2-only builds

- osbs/api.py
- tests/fake_api.py
Verified API call is being made as:
`2016-04-13 09:57:17,948 - osbs.http.out - DEBUG - GET /oapi/v1/namespaces/default/builds/?fieldSelector=status%3DRunning HTTP/1.1`
> Adding build status filter when fetching running builds

- osbs/build/spec.py
Follow-up on e0b77062f9087c12f1ce504fd68104fcae3d4704
> conf: build_host is not required anymore

- osbs/build/build_response.py
- tests/build/test_build_response.py
> BuildResponse: don't traceback on errorDetail logs

- osbs/api.py
- osbs/build/build_request.py
- osbs/build/spec.py
- tests/build/test_build_request.py
This is stored in the kojitask label of the BuildConfig.
> New koji_task_id parameter for create_prod_build()

- inputs/prod_inner.json
The store_metadata plugin now uses the result from the koji_promote plugin, so koji_promote needs to run before store_metadata.
> change order of exit plugins

- osbs/api.py
* Don't drop `status.lastVersion` from buildconfigs as this causes name collisions of newly created builds with restored builds.
* Don't drop `lastTriggeredImageID` because empty value may cause a rebuild from the same base image.
Closes #407.
> Fix backup processing

- osbs/cli/main.py
- osbs/core.py
This output would be used by zabbix-metrics script as its simplier and 
the output doesn't get cached
> watch-builds: support json output

- osbs/build/build_request.py
- tests/build/test_build_request.py
This is safe right now as it is not yet used.
> rename kojitask label 'koji-task-id'

- osbs/api.py
- osbs/core.py
- tests/constants.py
- tests/fake_api.py
- tests/test_api.py
This allows clients to filter listed builds by their koji-task-id label.
CC @lcarva, @breillyrh
> New optional koji_task_id parameter for list_builds.

- osbs/build/build_request.py
- tests/build/test_build_request.py
Change default for openshift_required_version.
This causes BuildConfig JSON to be created that is only handled correctly by OpenShift Origin 1.0.6 and later.
> Require OpenShift Origin >= 1.0.6 by default

- inputs/prod_inner.json
Currently image-id stored in annotations doesn't match the pulp image id
as we're not loading the squashed image back to Docker
> [WIP] prod_inner: use default dont_load setting for squash plugin

- inputs/prod_inner.json
Currently image-id stored in annotations doesn't match the pulp image id
as we're not loading the squashed image back to Docker
A duplicate of #426
> prod_inner: use default squash plugin settings

- osbs/api.py
- osbs/cli/main.py
- osbs/conf.py
- tests/test_api.py
- tests/test_conf.py
This parameter provides overrides for the labels in the Dockerfile. It cannot be set in the configuration file but can be provided at the command line.
Not providing configuration file compatibility because (a) it was never documented, and (b) config values would not get merged with CLI/kwarg values.
> new 'labels' optional parameter for create_prod_build()

- osbs/build/build_response.py
- osbs/cli/main.py
> hide logs and packages in get-build output if those are unavailable

- inputs/prod_inner.json
This can be merged, but a new release would require a release of atomic-reactor containing the following changes: https://github.com/projectatomic/atomic-reactor/pull/515
> Enable tag_from_config plugin

- osbs/api.py
- osbs/build/build_request.py
- osbs/build/spec.py
- osbs/conf.py
- tests/build/test_build_request.py
This also enables setting several secrets for a plugin and adds test.
Supersedes #443, as it contains suggestions from Tim and Luiz
> Support setting email/login/email for registries in tag_and_push plugin

- osbs/build/build_request.py
- tests/build/test_build_request.py
Depends on https://github.com/projectatomic/atomic-reactor/pull/521 so once merged we should wait until atomic-reactor is released with that change before releasing osbs-client.
> Configure pulp_sync with registry secret if provided

- osbs/build/build_response.py
- tests/build/test_build_response.py
This is handy for koji-containerbuild to return a more descriptive error message
> buildresponse: return a meaningful error message

- osbs/build/build_request.py
- tests/build/test_build_request.py
This unblocks builds using rhpkg, which doesn't pass git branch parameter
> Set git branch to empty string instead of None

- osbs/api.py
- osbs/build/build_request.py
- osbs/cli/main.py
- osbs/conf.py
- osbs/core.py
- tests/test_api.py
This creates a new build on existing BuildConfig (if found) instead of updating BuildConfig
TODO:
> Create a new Build for scratch builds

- osbs/api.py
- osbs/build/build_request.py
- osbs/build/spec.py
- osbs/conf.py
- tests/build/test_build_request.py
- tests/test_api.py
- tests/test_conf.py
When `unique_tag_only` is set to True, atomic-reactor will be configured to ensure built image is only tagged with its unique timestamp tag.
If `unique_tag_only` is either not set or set to False, behavior remains unchanged. This should allow using an older atomic-reactor version than the one containing these changes: https://github.com/projectatomic/atomic-reactor/pull/554
> Add support for unique_tag_only config

- osbs/cli/main.py
```
$ osbs --instance prod get-token --help
usage: osbs get-token [-h] [--oc]
optional arguments:
-h, --help  show this help message and exit
--oc        display oc login command
```
New `--oc` param in action:
```
$ osbs --instance prod get-token --oc
oc login --token ABCDEFGH0123 https://prod.example.com:9443/
```
Existing behavior is unaffected:
```
$ osbs --instance rcm-img-docker03-test get-token 
ABCDEFGH0123
```
> Add --oc to get-token for full oc login command

- tests/test_api.py
Fixes last missing test in #52 (https://github.com/projectatomic/osbs-client/issues/52#issuecomment-251637657)
> test_api: add test_create_build_from_buildrequest

- osbs/api.py
- osbs/core.py
- tests/test_api.py
When creating a Build directly OpenShift does not convert ImageStreamTag references to DockerImage references. In this circumstance, osbs-client needs to do this itself.
> Allow build_imagestream in conjuction with scratch=true

- inputs/prod_inner.json
Requires atomic-reactor >= 1.6.18 for:
https://github.com/projectatomic/atomic-reactor/pull/565
> Run distribution_scope pre-build plugin

- osbs/cli/main.py
Output will be quite (WARNING level) if -q, --quite option is present.
Verbose output (DEBUG level) will be produced if
--verbose option present
OR
verbose is set to true (1) in <config>/general.
Otherwise output has INFO level.
> Make --quiet flag work in CLI

- inputs/prod_inner.json
Only run this when Pulp is used and we are producing v2 images.
Depends on https://github.com/projectatomic/atomic-reactor/pull/574.
> configure pulp_pull plugin

- osbs/build/build_request.py
- tests/build/test_build_request.py
The compress plugin is only used by the koji_promote plugin now.
> scratch builds: don't run compress plugin

- osbs/api.py
- osbs/build/build_request.py
- osbs/build/spec.py
- osbs/conf.py
- tests/build/test_build_request.py
- tests/test_conf.py
Addresses a couple of issues:
1. If `builder_build_json_dir` is not defined, it properly falls back to `build_json_dir` from the `[general]` section. This was causing the `import_image` plugin to be configured with `build_json_dir` param as `None`.
2. Removed check for requiring `git_push_url` and `git_push_username` when using triggers. Also removed all references to those as there's no longer an intention to use them. Verified that if these values are in osbs.conf, they are simply ignored.
> Chain rebuild fixes

- osbs/api.py
- osbs/build/spec.py
- osbs/cli/main.py
- osbs/conf.py
- tests/test_api.py
I want to resolve #476 
-c is optional now, and has no effect whatsoever
instead of it, is used labels 'com.redhat.component' or 'BZComponent' from dockerfile
also made component label in dockerfile mandatory, if no found will raise exception
> -c is optional, and having no effect

- tests/test_api.py
Under Python 2.6 flexmock's `.with_args()` seems to be unreliable. In any case, in this particular instance we need custom handling to avoid having to predict the build name.
Provide a custom validator.
> test_scratch_build_config: avoid flexmock args comparison, and avoid race

- osbs/api.py
This was added to lookup 404 status_code symbol.
No need to depend on requests just for this.
> Remove unnecessary requests dependency

- osbs/cli/main.py
Output before looked like:
```
{'the-token': b'this-is-the-actual-token'}
```
Now it looks like:
```
this-is-the-actual-token
```
> Only display token for get-serviceaccount-token in CLI

- osbs/cli/main.py
```
$ osbs get-serviceaccount-token --help
usage: osbs get-serviceaccount-token [-h] [--oc] SERVICEACCOUNT
get auth token for serviceaccount
positional arguments:
SERVICEACCOUNT  name of the service account
optional arguments:
-h, --help      show this help message and exit
--oc            display oc login command
$ osbs get-serviceaccount-token spam
theSuperLongToken
$ osbs get-serviceaccount-token spam --oc
oc login --token theSuperLongToken https://api.mydomain.com:9443/
```
> Add --oc option to get-serviceaccount-token CLI

- inputs/prod_inner.json
- osbs/build/build_request.py
- tests/build/test_build_request.py
The client version should be in snake_case instead of kebab-case. The atomic-reactor object which handles the build JSON will ignore client_version but warn about client-version:
```
unprocessed keyword arguments: {u'client-version': ...}
```
> Fix name of client_version parameter in build JSON

- docs/configuration_file.md
- inputs/prod_inner.json
- osbs/build/build_request.py
- osbs/build/spec.py
- osbs/conf.py
- tests/build/test_build_request.py
This keyword causes the reactor_config plugin to be run, using the Kubernetes secret whose name is specified by the reactor_config_secret configuration keyword.
> Implement reactor_config_secret configuration keyword

- osbs/api.py
- tests/test_api.py
Usually API methods will wrap any exceptions in OsbsException. However, if the exception is e.g. a MethodCallError, perhaps because a function expected never to be called has been called, this may cause a test to pass and mask a bug.
Don't wrap MethodCallError or other flexmock expectation exceptions.
> Aid testing by not wrapping flexmock expectation exceptions

- osbs/core.py
- tests/test_core.py
Orchestration builds are running osbs-client inside the same container, where 
atomic-reactor runs, with a custom config. Some cluster, which didn't use 
kerberos could not be contacted, although correct config was provided.
The problem was in `__init__` function - it didn't qualify token as a sufficient 
credential and tried to read a serviceaccount token. This token is valid for 
orchestration cluster only and not for the target cluster.
This PR makes the token a valid authentication credential so that osbs client wouldn't try to read serviceaccount token if there is one in the configuration
> auth_credentials_provided should be set to true if token is specified

- osbs/api.py
- osbs/build/build_request.py
- osbs/build/spec.py
- osbs/conf.py
- tests/build_/test_build_request.py
- tests/test_api.py
- tests/test_conf.py
Removes the config option `unique_tag_only`. Its behavior is now implemented as part of `scratch` option.
In other words, when `scratch=True`, builds will only be tagged with a unique tag.
If `unique_tag_only` is defined in `osbs.conf`, it'll simply be ignored.
> consolidate unique_tag_only and scratch config

- osbs-client.spec
- osbs/__init__.py
- setup.py
- tests/test_osbs.py
Doing this can avoid dependency problems when installing using pip (when testing, for example).
https://www.python.org/dev/peps/pep-0440/#implicit-development-release-number
The rules for specfiles are that development release indicators go into the release field:
https://fedoraproject.org/wiki/Packaging:Versioning#Prerelease_versions
Next final release should be 0.36.
> Bump version number to development release

- osbs/build/build_request.py
Related: https://github.com/projectatomic/atomic-reactor/pull/676
> Configure koji_ssl_certs_dir for bump_release and koji plugins

- osbs/api.py
- osbs/build/spec.py
- osbs/constants.py
- osbs/utils.py
- tests/build_/test_build_request.py
- tests/build_/test_spec.py
- tests/test_api.py
As of now two scratch builds could have the same name,
due to the fact that build names were generated using a timestamp.
This changes is adding a random 5 digit number to the build names,
which should ensure uniqueness of the build names.
> Make scratch build names unique

- osbs/cli/main.py
There are no users of this argument, just remove it.
resolves #460
Signed-off-by: Don Zickus <dzickus@redhat.com>
> Remove unused --git-push-url cli argument

- .travis.yml
- osbs/build/build_request.py
- tests/test_api.py
Related: #556
Since the whole class is flexmocked in tests this has slipped: the class instance 
should store the received low_priority_node_selector
> Make sure BuildRequest has low_priority_node_selector set

- osbs-client.spec
- osbs/core.py
- osbs/http.py
- requirements.txt
- tests/test_core.py
- tests/test_http.py
This will work around an issue when pycurl is used in the same context as
rpm is, as used by koji-containerbuild.
Fixes #51
Signed-off-by: Patrick Uiterwijk puiterwijk@redhat.com
> Rewrite http.py to use python-requests

- osbs/core.py
- osbs/http.py
- tests/test_core.py
> core: trap ChunkedEncodingError along with of httplib.IncompleteRead, as python-requests throws two exceptions for different cases

- osbs/core.py
- osbs/http.py
- tests/test_core.py
This is to handle BadStatusLine-caused ConnectionErrors.
> core: trap ConnectionError and handle it like ChunkedEncodingError

- osbs/core.py
- osbs/http.py
- tests/test_core.py
- tests/test_http.py
The unit tests in `test_core.py` don't leverage the class HttpSession in http.py.
Instead they use the `Connection` class from fake_api.py.
Added additional tests in test_http.py to properly simulate behavior.
The except block in HttpStream.iter_lines didn't seem very useful.
When self.req.iter_lines is called, it returns a generator.
This wouldn't raise CheckedEncodingError, ConnectionError, nor IncompleteRead.
Those error cases are only valid when actually iterating through the generator, not during its creation.
The method decoded_json seemed to handle this properly. 
However, given that decoded_json is always used with iter_lines, I moved the correct error handling out of decoded_json and into iter_lines.
The errors we were seeing is because by the time the exception propagates to …
> Handle ConnectionError via OsbsException

- tests/test_conf.py
This also removed unused imports of os and namedtuple
Related to #579
> test_conf.py: don't mock argparse.Namespace with namedtuples as the latter don't support dots in names

- osbs/api.py
- osbs/conf.py
- tests/test_conf.py
Fixes #578
if platform exists at the time of build_request.set_params, read the
conf file for a variable node_selector.platform and return its value.
> get node_selector.platform values from conf

- osbs/build/build_request.py
- osbs/utils.py
- tests/build_/test_build_request.py
- tests/test_utils.py
The ancient setuptools in el7 behaves differently from more recent
setuptools, which results in unit test failures when running on an el7
host.
A quick illustration of the differences:
>>> from pkg_resources import parse_version
>>> parse_version('1.0.1')
<Version('1.0.1')>
>>> str(parse_version('1.0.1'))
'1.0.1'
>>> from pkg_resources import parse_version
>>> parse_version('1.0.1')
('00000001', '00000000', '00000001', '*final')
>>> str(parse_version('1.0.1'))
"('00000001', '00000000', '00000001', '*final')"
With this change, all 12 test failures I was previously encountering are
now passing. The key to this change is standardizing the old setuptools
output to look just like current setuptools output, using a new function
sanitize_version() in osbs/util.py, rather than calling …
> support old setuptools on el7

- osbs-client.spec
- osbs/cli/capture.py
- osbs/core.py
- osbs/exceptions.py
- osbs/http.py
- requirements.txt
- tests/fake_api.py
- tests/requirements.txt
- tests/test_api.py
- tests/test_core.py
OpenShift does not respond with any encoding value.
This causes requests module to guess it as ISO-8859-1.
Likely, the enconding is actually UTF-8, but we can't
guarantee it. Therefore, we take the approach of simply
passing through the encoded data with no effort to
attempt decoding it.
> no longer attempt to decoded streamed build logs

- inputs/orchestrator_inner:1.json
- inputs/worker_inner:1.json
- osbs/build/build_request.py
- tests/build_/test_build_request.py
[Looking for early feedback]
Currently if the spec provides a 'release' param, it is not passed along
to the orchestrator as a label.  Detect that and provide it.  Also remove
the bump_release plugin if the 'release' param is passed in.
Updated tests to verify change.
Signed-off-by: Don Zickus <dzickus@redhat.com>
> build_request: Set 'release' label when provided

- osbs/__init__.py
- osbs/api.py
- osbs/build/__init__.py
- osbs/build/build_request.py
- osbs/build/spec.py
- osbs/cli/main.py
- osbs/cli/render.py
- osbs/conf.py
- osbs/core.py
- osbs/utils.py
- tests/build_/test_build_request.py
- tests/build_/test_build_response.py
- tests/cli/test_capture.py
- tests/fake_api.py
- tests/test_conf.py
- tests/test_core.py
- tests/test_exceptions.py
- tests/test_utils.py
- tests/throughput-test-harness.py
I ran flake8 on osbs/ and tests/ and fixed all the long lines, incorrect
whitespace, and unused variables.
The only functional change was in tests/build_/test_build_request.py:
@@ -1238,7 +1230,7 @@ class TestBuildRequest(object):
if isinstance(worker_build_image, type):
with pytest.raises(worker_build_image):
worker_config_kwargs['build_image']
-                worker_config.get_build_image() == None
+                assert not worker_config.get_build_image()
which converts a nonsense statement into the intended assert.
> janitorial: clean up whitespace and other linter errors

- osbs/cli/main.py
Namespace is set in the config already, its not being passed as an arg
> backup-builder: don't append namespace in the filename

- osbs/conf.py
- tests/test_conf.py
If platform is a valid string, but node_selector.platform = None in the
config file, the existing code will do the wrong thing. Make sure that the
parsed item for node_selector.platform has '=' in it or ignore it.
Add test cases for the node_selector.platform = None path.
> get_platform_node_selector: handle node_selector.platform = None

- osbs/api.py
Maintaining the code for all-in-one builds will become harder
over time. The sooner we can remove create_prod_build(), the
easier we will make future maintenance.
> Deprecate create_prod_build

- docs/configuration_file.md
- osbs/conf.py
Also allow literal none for low_priority_node_selector, for consistency with how node_selector.(platform) works.
> Add documentation for node_selector.(platform)

- tests/build_/test_arrangements.py
Each supported arrangement version can be tested by inheriting
from the previous TestArrangementVn object and testing the
expected changes.
> Initial testing for arrangement versions

- tests/test_api.py
test for what version of builtins and input_str we need before making
the flexmock call, not afterwards.
> test_login_api: better flexmock invocation

- osbs/api.py
- osbs/build/config_map_response.py
- tests/mock_jsons/0.5.4/create_config_map.json
- tests/mock_jsons/1.0.4/create_config_map.json
- tests/test_api.py
Encode the data as json object pairs to handle nested dictionaries.
> ConfigMap API: better data encoding

- osbs/api.py
- osbs/build/build_request.py
- osbs/build/spec.py
- tests/build_/test_build_request.py
This new parameter is needed when creating worker builds when Koji integration is required.
> Handle koji_upload_dir parameter in build request

- osbs/cli/main.py
When starting a build via osbs-client from CLI via `build` subcommand, some critical information gets buried in the logs. This is an attempt to provide user the information needed for pulling image built image, and further inspect OpenShift build if needed.
Example for a successful build:
```
build atomic-reactor-hello-world-master-0d3e8-27 is complete
unique repositories:
registry.example.com/lucarval/docker-hello-world:none-99021-20170703191647
primary repositories:
registry.example.com/lucarval/docker-hello-world:7.2.lucarval
registry.example.com/lucarval/docker-hello-world:7.2.lucarval-106
registry.example.com/lucarval/docker-hello-world:latest
```
> display build summary once build is complete

- osbs/constants.py
OSBS client will need the atomic_reactor logs in a specific format
in order to parse them correctly.  Control that in osbs-client and
make it available for atomic_reactor to import.
> constants: Add logging format for atomic_reactor

- osbs/api.py
- osbs/build/build_request.py
- osbs/constants.py
- osbs/repo_utils.py
- osbs/utils.py
- tests/build_/test_arrangements.py
- tests/build_/test_build_request.py
- tests/test_api.py
- tests/test_repo_utils.py
If configuration file in git repo has been set to enable
autorebuilds, Dockerfile must also not have "release" label set.
If so, build now fails to start to avoid confusion.
Additionally, if configuration has been set to disable autorebuild,
image change triggers are automatically removed from BuildConfig.
This avoids unwanted auto builds.
> Consult git repo when enabling autorebuilds

- osbs/build/build_request.py
- tests/build_/test_arrangements.py
remove worker_fetch_metadata from scratch builds and make sure that
test_arrangement tests is properly.
> koji_import: don't call worker_fetch_metadata in scratch builds

- tests/build_/test_arrangements.py
This tests both worker and orchestrator running orders.
> Fix name of 'running order' test

- osbs/api.py
- osbs/constants.py
- osbs/core.py
- osbs/http.py
- tests/test_api.py
- tests/test_core.py
- tests/test_http.py
Initial version of retries in http.py
How to test:
* `sed -i '557s/.*/            response.status = 500 if url.startswith("\/oapi") and method == "GET" and retries._observed_errors == 0 else response.status/' /usr/lib/python2.7/site-packages/urllib3/connectionpool.py` in buildroot and on builder
* start a build via osbs
* the build should pass and buildlog should have warning that Openshift requests were retried once, as first request would always return HTTP 500
TODO:
> Implement retries in osbs-client's HTTP requests

- osbs/api.py
- osbs/build/build_request.py
- osbs/conf.py
- tests/build_/test_build_request.py
- tests/test_conf.py
add support to Configuration to parse platform: sections, as described at
http://osbs.readthedocs.io/en/latest/multiarch.html#platform-description.
change get_registry_api_versions to take a platform argument. If there
is a platform argument, only return 'v1' if the configured api version
supports it and that platform value has enable_v1 set to True. Otherwise,
return v2. If the platform doesn't enable v1 and the registry is v1 only,
raise an exception.
Also raise an exception if two platforms have enable_v1 set to true.
A stub instance of render_group_manifests() is included, but since
group_manifests isn't in any of the existing arrangements, it will do
nothing for now in practice.
> conf: add support for "platform:..." sections

- osbs/conf.py
- tests/build_/test_build_request.py
- tests/test_conf.py
orchestrator builds never have platforms, but should always return the
registry_api_versions values from their config file, or ['v1', 'v2'] if
that is undefined.
> conf: fix get_registry_api_version for orchestrator

- osbs/build/build_request.py
- tests/build_/test_build_request.py
pulp_pull is required to set koji metadata only
> Remove pulp_pull from scratch build request or when kojhub is not specified

- osbs/api.py
- osbs/cli/main.py
- tests/test_api.py
This adds support for (utf-8 only) log decoding within the
get_build_logs() api method. Ideally, we would clean up the return types
to be more consistent (None or iterable bytes), but for interoperability
with current atomic-reactor, we'll continue to return either None, bytes,
or an iterable of bytes, entirely dependent on what we're fed by the
self.os.logs() call within get_build_logs().
Note: osbs/cli/main.py's calls to get_build_logs have also been updated to
use decode=True, which is a bit of a behavioral change for end-users, but
probably for the better, since the caller mostly just print out whatever
they're handed back, which should look better if fully decoded. The
behavior of any external caller should remain the same.
Signed-off-by: Jarod Wilson <jarod@redhat.com>
> osbs/api: add decode parameter to get_build_logs

- inputs/orchestrator_inner:4.json
- osbs/build/build_request.py
- tests/build_/test_arrangements.py
Moving the delete_from_registry plugin from worker to orchestrator
invovles adding a new arg, 'insecure', to pass in.
The reason is on the worker node, add_docker_registry sets the 'insecure'
flag from another plugin and delete_from_registry just leverages that.
But on the orchestrator, the workflow.push_conf docker registries are
not defined and instead are passed through worker annotations.  Those
annotations do not set 'insecure'.  Change the json file to include
it during 'render'.
The plugin is still backwards compatible with previous arrangement
versions.
> pulp_sync: Update delete_from_registry plugin with new args

- inputs/orchestrator_inner:4.json
- osbs/build/build_request.py
- tests/build_/test_arrangements.py
- tests/build_/test_build_request.py
commits to enable group_manifests, pulp_tag, and pulp_publish in arrangement 4.
tested with brew-pulp-docker01.web.prod.ext.phx2.redhat.com:8888/mlangsdo/buildroot:eng-rhel-7-docker-candidate-94693-20170816174925, which is a build of pkgs.devel.redhat.com/rpms/osbs-buildroot-docker@private-mlangsdorf-incremental
that uses:
https://github.com/mlangsdorf/atomic-reactor.git@arrangement4
https://github.com/mlangsdorf/osbs-client.git@arrangement4
build logs are here:
https://osbs.qa.engineering.redhat.com:8443/console/project/osbs-stage/browse/builds/helloworld-container-master-9bc2a/helloworld-container-master-9bc2a-77?tab=logs
> Fix rendering for Pulp plugins in arrangement version 4

- docs/configuration_file.md
- osbs/api.py
- osbs/build/build_request.py
- osbs/build/spec.py
- osbs/conf.py
- tests/build_/test_arrangements.py
- tests/fake_api.py
set group for post_group_manifests to true when the configuration file
has the pulp_manifest_lists value set to true to indicate the pulp
repository supports manifests lists.
> build_request: render_group_manifests now supports true grouping

- docs/configuration_file.md
- osbs/api.py
- osbs/build/build_request.py
- osbs/build/spec.py
- osbs/conf.py
- tests/build_/test_build_request.py
When defined, this configuration option is passed to koji_upload
plugin so it can be used in deciding which manifest should be
used in the build output files.
This option is also forwarded to worker builds.
> Add prefer_schema1_digest configuration option

- osbs/repo_utils.py
- tests/test_repo_utils.py
When processing of additional-tags file was moved to
osbs-client from atomic-reactor, the validation check
became more permissive. This commit ports the validation
algorithm from atomic-reactor's tag_from_config plugin.
> Perform stricter validation of additional tags

- osbs/build/build_request.py
- tests/build_/test_arrangements.py
This parameter is used to report schema 1 and schema 2 image manifest digests. Once Pulp content has been synced in, any digests not present will be removed from the metadata.
Relates to https://github.com/projectatomic/atomic-reactor/pull/822
> Set koji_upload's report_multiple_digests parameter

- osbs/build/spec.py
Flatpak builds fail with `OsbsValidationException: base_image must be provided`
> spec.py: don't track base image for flatpak builds

- .travis.yml
- osbs-client.spec
- test.sh
- tests/test_http.py
Benefits of this approach:
* Travis failures can be reproduced locally: `sudo env OS=centos OS_VERSION=7 ./test.sh` or `sudo env OS=fedora OS_VERSION=26 PYTHON_VERSION=3 ./test.sh`. By default it would run tests on CentOS 6
* Tests would run against actual packages in distributions, not latest from pypi
* Spec files dependencies are tested as well, so less surprises for Fedora packagers during `%check` phase
> Rework travis to make it run in different Fedora/CentOS containers

- osbs/build/build_request.py
- tests/build_/test_build_request.py
When enabled in *_inner.json, import_image plugin needs to run
for all builds, even the ones that do not have autorebuild
enabled. Importing image into OpenShift affects the layered
images which may have autorebuild enabled.
> Always leave import_image enabled

- osbs/core.py
- tests/test_core.py
The API method import_image is used to force OpenShift to
update the tags tracked in the corresponding ImageStream
object. To do so, the following annotation is cleared:
"openshift.io/image.dockerRepositoryCheck"
The problem addressed by this commit is that in the case
an ImageStream does not pick up new tags, the API method
may hang indefinitely. Removing this annotation causes
OpenShift to actually "force" the import and reset the
annotation.
> Make import_image remove dockerRepositoryCheck

- osbs/conf.py
- tests/test_conf.py
This might lead to a wrong `OsbsValidationException('v2 only platform in v1 only instance')` error if space is put after a comma
> conf.py: strip spaces when parsing values, separated by comma

- osbs/api.py
- tests/test_api.py
Remove koji task id from build config if build was created explicitly.
> Remove koji-task-id from build config

- tests/test_http.py
- tests/test_retries.py
This breaks tests on Fedora's koji, as tests are being run there
without network access.
This PR does the following:
* Don't retry when detecting if network connection is available
* Trap `requests.exceptions.ConnectionError` as its being thrown too.
Test build in Fedora: https://koji.fedoraproject.org/koji/taskinfo?taskID=22993054
> tests: update has_connection detecting

- osbs/cli/main.py
When triggering builds with osbs-client cli and using the
--compose-id option to specify composes to be used,
the following TypeError is raised when logging the ID of
a compose which is going to be renewed:
TypeError: %d format: a number is required, not unicode
This is due to the compose IDs being received as unicode
strings from the cli.
Setting the type for the argument to int solves this issue.
Signed-off-by: Hunor Csomortáni <csomh@redhat.com>
> Convert the value of --compose-id to int

- osbs/build/build_request.py
- tests/build_/test_arrangements.py
- tests/build_/test_build_request.py
The code was checking for spec.imagestream_name is None not
spec.imagestream_name.value is None - this was never noticed because
spec.imagestream_name is now always set except for Flatpak builds and
previously, a different check was removing the plugin first.
Check in tests that the plugin is properly removed for Flatpak builds.
> render_import_image: fix logic for checking imagestream_name/url

- osbs/api.py
- osbs/build/build_request.py
- osbs/repo_utils.py
- osbs/utils.py
- tests/build_/test_arrangements.py
- tests/build_/test_build_request.py
- tests/test_api.py
If container.yaml file in the git repository contains tags section,
resulting image is created with these tags only.
Signed-off-by: David Becvarik <dbecvari@redhat.com>
As this is working, if the tags are missing image-version tag it will die in this [this assertion](https://github.com/projectatomic/atomic-reactor/blob/56299e323d9904248746282569a9c32f5353c547/atomic_reactor/plugins/exit_koji_import.py#L294).
I don't have a deep understanding how to solve this issue, because I'm missing bigger picture how whole OSBS/koji works inside. 
I've noticed that for scratch build this plugin is not used? 
Can we also disable it for this custom tags builds (but this feels very weird)?
@goldmann Or maybe, we can add this tag as always present ?
> Added possibility to override image tags via container.yaml file.

- inputs/worker_inner:4.json
- osbs/build/build_request.py
- tests/build_/test_arrangements.py
- tests/build_/test_build_request.py
With the switch to "hybrid" modularity in Fedora, modules typically need
to pull packages from a base package set as well. The build tag of the
Koji target provides a way to pass in an appropriate base package set, so
we'll use the 'koji' plugin for that.
>  Don't exclude the 'koji' plugin for Flatpaks

- osbs/build/build_request.py
- tests/build_/test_build_request.py
> don't remove reactor_config plugin if config_map is provided

- inputs/orchestrator_inner:7.json
- inputs/worker_inner:7.json
- osbs/api.py
- osbs/build/build_request.py
- osbs/build/build_requestv2.py
- osbs/build/plugins_configuration.py
- osbs/build/spec.py
- osbs/build/user_params.py
- osbs/constants.py
- tests/build_/test_build_requestv2.py
- tests/build_/test_plugins_configuration.py
- tests/build_/test_spec.py
- tests/build_/test_user_params.py
As part of the move to arrangement 6, create PluginsConfiguration, BuildRequestV2 and the
underlying BuildUserParams.
(move from PR733 because github keeps stalling out on me).
Currently the templates are *_inner:7.json to avoid collisions with the DEFAULT_ARRANGEMENT_VERSION tests.
Please review.
Signed-off-by: Mark Langsdorf mlangsdo@redhat.com
> Arrangement 6: Add support for BuildUserParams, BuildRequestV2, and PluginsConfiguration

- osbs/build/build_request.py
- tests/build_/test_arrangements.py
- tests/build_/test_build_request.py
This parameter is used by add_filesystem plugin to select the arch
specific filesystem tarball.
> Set architecture parameter for add_filesystem

- osbs/build/build_requestv2.py
- osbs/build/plugins_configuration.py
- osbs/build/user_params.py
- tests/build_/test_arrangements.py
- tests/build_/test_plugins_configuration.py
A handful of fixes for arrangement 6
* add koji_upload_dir to BuildUserParams and koji_upload's rendered args
* remove build_json_dir from the args of some plugins
* change the way that labels are passed to add_labels_in_df
works with https://github.com/projectatomic/atomic-reactor/pull/964
> fixes for arrangement 6

- osbs/build/plugins_configuration.py
- tests/build_/test_plugins_configuration.py
it's an optional argument but it's a user params.
> arrangement 6: pass koji_target to resolve_composes

- osbs/build/spec.py
Docker versions since 1.12 have not placed any minimum length requirement on the namespace portion of a repository name.
Reference: https://github.com/moby/moby/commit/6f0068f
Fixes #552.
> Don't pad short usernames (OSBS-5391)

- osbs/constants.py
The information required by OSBS is fully stored in BuildConfig and
ImageStream objects. Additionally, the Build objects are only restored
if they don't have a BuildConfig associated with them. Those are scratch
and isolated builds which we care very little about backing up in OSBS.
> Don't backup Build objects

- inputs/orchestrator_inner:6.json
- tests/build_/test_arrangements.py
This allows check_and_set_rebuild plugin to modify the current git
commit before other plugins read from git clone.
> Run check_and_set_rebuild plugin earlier

- osbs/http.py
- tests/test_http.py
Currently, if the json string received from a _get is corrupt and
can't be converted, the json package raises a cryptic message about
extra data, but doesn't provide the bad string.
Catch that exception and raise an error with more detail about what
went wrong and the full string that was being loaded.
This doesn't fix osbs-5424, but will hopefully make it easier to
determine what went wrong the next time someone sees a similar failure.
> HttpResponse: better error message when json is corrupt

- osbs/http.py
- tests/test_http.py
Remove the try/except sequence from iter_lines(), so that any exceptions
generated by the req.iter() will be propagatetd unchanged up the stack.
Add a test case to prove that an exception in HttpStream.iter_lines()
will move up the stack.
> HttpStream: don't catch exceptions in iter_lines

- osbs/conf.py
- tests/test_conf.py
A lot of conf arguments have been deprecated and moved to reactor_config_map.
Replace _get_value with _get_deprecated and print a warning message for
all get_* functions in conf where the value is not in the accepted parameters
list for BuildRequestV2.
> arrangement 6: add deprecation warnings to conf.get_*

- osbs/conf.py
> conf: fix errant comma in deprecation warnings

- osbs/conf.py
- tests/test_conf.py
only print deprecation warnings for cli args and file args, not for kwargs.
> conf: quieter deprecation warnings

- osbs/api.py
- osbs/build/build_response.py
- osbs/cli/main.py
- tests/build_/test_build_response.py
add a new function to BuildReponse that returns the error reason: either the error message
from the build metadata if that exists, or from the pod's failure reason if that exists.
this new function will also be called by atomic reactor's build_orcestrate_build plugin, to
replace the current code for getting failures from a worker build.
change get_error_message() to use this new function also.
> build response: better error messages

- osbs/http.py
The Retry class retries connection failures forever by default.
Limit this the same way we limit other retryable errors.
Tested using:
```
$ cat osbs.conf 
[default]
openshift_url = http://localhost:9001/
$ osbs --conf osbs.conf --verbose watch-builds 
2018-06-14 10:39:08,763 - osbs - DEBUG - Logging level set to debug
Traceback (most recent call last):
File "/usr/lib/python3.6/site-packages/urllib3/connection.py", line 142, in _new_conn
(self.host, self.port), self.timeout, **extra_kw)
File "/usr/lib/python3.6/site-packages/urllib3/util/connection.py", line 83, in create_connection
raise err
File "/usr/lib/python3.6/site-packages/urllib3/util/connection.py", line 73, in create_connection
sock.connect(sa)
ConnectionRefusedError: [Errno 111] …
```
> Limit the number of automatic connection attempts

- .travis.yml
Signed-off-by: Clement Verna <cverna@tutanota.com>
> Fedora 26 is EOL, replace it by Fedora 28 in travis CI

- osbs/core.py
- osbs/exceptions.py
- osbs/utils.py
- tests/test_core.py
In some cases, the container registry used may return a 500 error
response when image is fetched by OpenShift via ImageStream. This has
been seen when using pulp+crane container registry.
This change will verify that each requested imported tag was successful.
If not successful, and container registry has returned a 500 error, the
import image operation is retried.
> Check import-image response and retry if needed

- osbs/build/plugins_configuration.py
- tests/build_/test_plugins_configuration.py
This was implemented for build_request.py in 3c18d4bb44, but the change
never made its way into plugins_configuration.py.
> plugins_configuration.py: Don't exclude the 'koji' plugin for Flatpaks

- osbs/build/plugins_configuration.py
- tests/build_/test_plugins_configuration.py
For Flatpak builds, handling of composes is done in
resolve_module_compose, so the 'resolve_composes' plugin just duplicates
this and causes things to go wrong.
> Don't include 'resolve_composes' for Flatpak builds

- osbs/build/plugins_configuration.py
- osbs/build/user_params.py
- tests/build_/test_plugins_configuration.py
Without this we are trying to run the pre_flatpak_create_dockerfile plugin when trying to build normal containers.
Maybe @mlangsdorf could review this and make sure this is a sane change.
I ll be happy to work on some tests if I could get some pointers on which test to modify.
cc'ing @owtaylor 
Signed-off-by: Clement Verna <cverna@tutanota.com>
> Do not load the flatpak_create_plugin if we are not building a flatpak

- osbs/build/plugins_configuration.py
- tests/build_/test_plugins_configuration.py
There was a lot of (barely used) complexity in atomic reactor to handle the check_and_set_platforms plugin being only run for builds with koji_target. Including it for all orchestrated builds allows us to simplify that logic. (This does introduce incompatibility with older atomic-reactor for the rarer case of builds missing koji_target.)
See https://github.com/projectatomic/atomic-reactor/pull/1046 for the atomic-reactor piece.
This PR also contains a patch to fix the parameterization of the check_and_set_platforms test.
>  Always include check_and_set_platforms for orchestrated builds

- test.sh
Version 1.6.0 of the py module is incompatible with Python-2.6.
This should get the Travis build working again. Trying to test against Python-2.6 may not be sustainable long term :-)
> test.sh: Force py == 1.5.4 on Centos 6

- osbs/api.py
- tests/test_api.py
> use build for koji id if already exists, fix use json method instead of attribute from get_build

- inputs/orchestrator_inner:6.json
- tests/build_/test_arrangements.py
I didn't remember the key name for exit_verify_media_types.py correctly, and put the wrong value in
orchestrator_inner:6.json and test_arrangements.py.  Because I used the wrong value in 
test_arrangements, it didn't detect that I'd put the wrong value in orchestrator_inner:6.json.
Correct that mistake.
Also, use the key values in test_arrangements.py as a hedge against this mistake in the future.
> verify media types: fix an incorrect name in json, add tests to avoid that mistake in the future

- osbs/build/plugins_configuration.py
- tests/build_/test_plugins_configuration.py
atomic_reactor will be enhanced to allow signing_intent to be passed
for Flatpak builds as well. If a signing intent is specified, pass that
as a parameter to the resolve_module_compose plugin. (Compatiblity
with old atomic-reactor versions is retained in the case where signing
intent is not specified.)
> PluginsConfiguration: allow signing_intent for Flatpaks

- .travis.yml
Without install section, travis do default `pip install -r
requirements.txt` and we don't need it. It only slowdowns builds.
> Travis: add install section

- osbs/build/plugins_configuration.py
- tests/build_/test_plugins_configuration.py
Flatpaks are OCI images, and currently Pulp doesn't have OCI image support.
To avoid failures trying to upload to Pulp, simply omit all pulp-related
plugins for Flatpak builds. (The resulting Flatpaks will still be
uploaded to Koji, and to any configured Docker registries with OCI support.)
> Remove pulp plugins for Flatpak builds

- inputs/orchestrator_inner:6.json
- tests/build_/test_arrangements.py
Deleting content from the registry after pulp finishes syncing is
convenient so the next pulp sync will not take longer (pulp iterates
over the repository tags fetching all referenced content). However,
removing content may confuse the docker distribution registry, which
leads to failing builds.
> Disable delete_from_registry plugin

- tests/build_/test_plugins_configuration.py
This plugin has been deactivated in 9cb8b97 (PR #813), which was merged without a rebase for the PR #815 changes, causing the related test to fail.
This removes the deactivated plugin from the expected plugins list for non flatpack builds, which fixes the issue.
> Remove delete_from_registry plugin checks

- osbs/api.py
- osbs/build/build_request.py
- osbs/build/build_requestv2.py
- tests/build_/test_build_request.py
- tests/build_/test_build_requestv2.py
- tests/test_api.py
FROM scratch images cannot be built as isolated builts.
> Prohibit isolated FROM scratch builds

- osbs/api.py
- osbs/build/build_request.py
- osbs/build/build_requestv2.py
- osbs/build/plugins_configuration.py
- osbs/build/spec.py
- osbs/build/user_params.py
- osbs/conf.py
- tests/build_/test_arrangements.py
- tests/build_/test_build_request.py
- tests/build_/test_build_requestv2.py
- tests/build_/test_plugins_configuration.py
> remove flatpak_base_image

- .pylintrc
- .travis.yml
- osbs/api.py
- osbs/core.py
- osbs/http.py
Python 3.7 enables PEP 479, meaning that direct calls to StopIterator in
generators will raise RuntimeError exceptions. We deprecate the usage of
such calls in favor of calls to return, keeping the desired behavior and
complying to PEP 479.
* https://docs.python.org/3.7/whatsnew/3.7.htm
* https://www.python.org/dev/peps/pep-0479/
> Comply to PEP 479 to support Python 3.7

- osbs/api.py
- tests/test_api.py
Koji doesn't collect stderr/stdout only logger, so warning.warn() output
is not shown in collected logs.
> Use logger for warnings

- .travis.yml
- osbs-client.spec
- osbs/api.py
- osbs/build/build_request.py
- osbs/build/plugins_configuration.py
- osbs/build/pod_response.py
- osbs/build/spec.py
- osbs/cli/capture.py
- osbs/cli/main.py
- osbs/conf.py
- osbs/core.py
- osbs/http.py
- osbs/utils.py
- test.sh
- tests/build_/test_user_params.py
- tests/fake_api.py
- tests/test_api.py
- tests/test_core.py
- tests/test_http.py
- tests/test_repo_utils.py
- tests/test_retries.py
- tests/throughput-test-harness.py
We are dropping Python 2.6 support. Note that when this gets merged, atomic-reactor test suite should also be changed not to run on python 2.6 environments.
> Drop Python 2.6 support

- docs/backups.md
- docs/development-setup.md
- docs/osbs_instance_setup.md
Explicitly reference the oc client as the OpenShift Client with up to
date Fedora package references for both the `oc` binary and the
OpenShift Origin packages.
* Closes #569
> docs: Update OpenShift references

- tests/requirements.txt
CentOS 7 setuptools version does not accept a list of requirements
containing wildcards. We do skip tests for rhel<=7 builds, but the
python2 build macro calls setuptools, which verifies the test
requirements listed in setup.py. Using wildcards in requirements will
break RPM builds for such systems.
**A similar change is not required in atomic reactor since the test requirements are not listed in setup.py for that project**
> Freeze requirements minor versions for RPM builds

- osbs/api.py
- osbs/build/build_request.py
- osbs/build/build_requestv2.py
- osbs/build/plugins_configuration.py
- osbs/build/user_params.py
- tests/build_/test_user_params.py
Atomic-reactor will use digests instead of tags for builds to prevent
race conditions caused by floating tags of paretn images. For this
reason osbs-client must provide this information in request
Jira: OSBS-5674
> Extend build_json with images digests data

- docs/build_process.md
- docs/configuration_file.md
- osbs/build/build_request.py
- osbs/conf.py
- osbs/utils.py
- tests/build_/test_build_request.py
- tests/build_/test_spec.py
- tests/test_conf.py
We no longer need to handle the case where we are not pushing to a v2
registry.
> Remove support for v1-only registries

- osbs/repo_utils.py
- tests/test_repo_utils.py
Container yaml file can may contain empty keys. We must handle them on
when fetching values from the file.
Also adding a couple tests to cover this case.
> Handle null values for composes in container yaml

- osbs/build/plugins_configuration.py
- tests/build_/test_arrangements.py
- tests/build_/test_plugins_configuration.py
now that custom base images are handled by the plugins themselves,
there's no need to edit the plugins JSON to deal with them.
> plugins configuration: remove special handling for custom base images

- osbs-client.spec
- osbs/cli/render.py
- osbs/constants.py
- osbs/utils.py
- tests/test_utils.py
The retry code is based on atomic-reactor's backoff and retry operations [1]. A next step would be to reuse osbs git checkout function in atomic-reactor.
[1] https://github.com/projectatomic/atomic-reactor/blob/e8294b8df36660097db463060fe9610ddf7f7cbb/atomic_reactor/util.py#L305 (the ref points to master's HEAD on the day this PR was open)
> Retry git clone operations

- osbs/api.py
- tests/test_api.py
If osbs-client fails when a Dockerfile cannot be parsed, it fails with
`osbs - ERROR - Exception caught: OsbsException: IOError(2, 'No such file or directory') (from IOError(2, 'No such file or directory'))`
This commit captures a possible IOError when DockerfileParser tries to
read a Dockerfile and re-raise it with a friendly error message.
> Capture and re-raise DockerfileParser IOError

- osbs/api.py
- tests/test_api.py
This is critical to allow Freshmaker to rebuild container images to
address CVEs.
> Allow isolated builds for custom base images

- test.sh
We cannot read verbose output nicely in travis output because it is trimmed.
> Don't run pytest in verbose mode

- osbs/constants.py
- osbs/repo_utils.py
- osbs/utils.py
- tests/build_/test_arrangements.py
- tests/constants.py
- tests/test_api.py
- tests/test_utils.py
merge the logic of atomic-reactor's clone_git_repo with osbs-client's
checkout_git_repo while adding support for passing depth values to
both and performing shallow clone operations if possible.
> utils: refactor git clone operations to share code with atomic-reactor

- osbs/api.py
- osbs/build/plugins_configuration.py
- osbs/build/user_params.py
- osbs/utils.py
- tests/build_/test_arrangements.py
- tests/build_/test_plugins_configuration.py
- tests/build_/test_user_params.py
- tests/test_api.py
- tests/test_utils.py
Reduce the amount of load on the git servers:
* Pass the git repo configuration information (container.yaml, additional tags, and such) to atomic reactor as part of the user parameters of the build JSON, so that atomic reactor doesn't need to reclone the repo to get that information.
* Refactor plugins configuration slightly so that the additional tags for `tag_from_config` are taken from the build configuration, instead of recloning the git repo
* Calculate the depth of the commit when cloning the repo for the first time, and pass that information to as part of the git repo configuration information.  Subsequent clones of the repo clone (for worker builds, etc) clone using --depth, dramatically reducing the amount of data that needs to be transferred.
Atomic reactor will need changes to …
> minimize the work of git clone

- .pylintrc
- osbs/api.py
- osbs/build/user_params.py
- osbs/cli/main.py
- osbs/core.py
- osbs/repo_utils.py
- osbs/utils.py
- tests/__init__.py
- tests/build_/test_arrangements.py
- tests/build_/test_build_request.py
- tests/build_/test_build_requestv2.py
- tests/build_/test_build_response.py
- tests/build_/test_manipulate.py
- tests/build_/test_plugins_configuration.py
- tests/build_/test_pod_response.py
- tests/build_/test_spec.py
- tests/build_/test_user_params.py
- tests/cli/test_capture.py
- tests/test_api.py
- tests/test_cli.py
- tests/test_conf.py
- tests/test_core.py
- tests/test_http.py
- tests/test_osbs.py
- tests/test_repo_utils.py
- tests/test_retries.py
- tests/test_utils.py
- tests/throughput-test-harness.py
You don't want to know how long it took me to figure out why `from six.moves import input` broke tests.
> Fix py2/3 compatibility issues

- osbs/build/config_map_response.py
- osbs/repo_utils.py
`yaml.safe_load` must be used for user input to prevent injecting
malicious objects.
> CVE-2019-10135: insecure yaml load of user input

- docs/configuration_file.md
- osbs/api.py
- osbs/build/build_requestv2.py
- osbs/build/user_params.py
- osbs/conf.py
- osbs/constants.py
- tests/build_/test_build_requestv2.py
- tests/build_/test_user_params.py
For osbs #7519
Set a completionDeadline of 3 hours in a worker or 4 hours in the orchestrator.  This should automatically cancel stuck builds.  Alternate values can be set in the config file and the deadline can be disabled altogether by using negative values.
> build request: set a completion deadline

- osbs/cli/main.py
This will prevent encoding errors when running osbs-client CLI
* OSBS-6632
> Use repr when printing logs for cli builds

- Dockerfile
Update the "FROM" line to the latest stable Fedora release.
Several of the python2 packages are no longer available, so switch everything entirely over to Python 3.
> Dockerfile: update for Fedora 30

- osbs/utils.py
Prior to this change, when a user specified a registry URI that completely fails to match our validation regex, `match()` returned None, and we called `.groups()` on that `None` value. This led to the following error message:
```
osbs.exceptions.OsbsException: AttributeError("'NoneType' object has no attribute 'groups'")
```
Handle the case where our regex does not match the user input and raise
a more helpful error message to the user.
> utils: better error message when we fail to parse registry URI

- osbs/build/plugins_configuration.py
The log message is a single-quoted string. We don't need any double-quotes here.
> build: remove stray quote from debug log message

- osbs/build/user_params.py
- tests/build_/test_user_params.py
Prior to this change, when a user specified a `--build-from` option that does not contain a "`:`" character, `split()` returned one value, but we tried to assign the result to two values (`source_type` and `source_value`). This led to the following error:
```
osbs.exceptions.OsbsException: ValueError('not enough values to unpack (expected 2, got 1)')
```
Handle the case where the user fails to specify "`:`" by returning a more helpful error message to the user.
> user_params: better error for missing ":" in build-from

- osbs/cli/main.py
Show the default `osbs.conf` and the default configuration section title ("default") path when the user runs `osbs --help`.
> cli: show default config options in --help

- osbs/api.py
- osbs/build/user_params.py
- tests/build_/test_user_params.py
> Sources containers user build params

- osbs/build/user_params.py
Accidentally this class was not marked as abstract
> User params: make BuildCommon an abstract class

- osbs/constants.py
> constants: fix "deadlines" spelling in comments

- inputs/orchestrator_sources_inner:6.json
- tests/build_/test_plugins_configuration.py
> Fix build plugin name in inner

- inputs/orchestrator_inner:6.json
- tests/build_/test_arrangements.py
Add exit_push_floating_tags to inputs/orchestrator_sources_inner:6.json,
and reorder exit_import_image to run after it.  If exit_koji_import
fails, push_floating_tags and import_image shouldn't run, but
import_image needs to run on the floating tags.
> push_floating_tags: Add plugin to inputs/

- osbs/utils.py
- tests/build_/test_user_params.py
NVRs should be split twice instead of three times. This allows names
with dashes on them (as they are allowed in Koji).
> Fix source container NVR split

- osbs/api.py
- osbs/build/user_params.py
- osbs/cli/main.py
- tests/build_/test_user_params.py
> pass sources_for_koji_build_id to sources build

- inputs/orchestrator_sources_inner:6.json
- osbs/build/plugins_configuration.py
> Source containers: enable required plugins

- osbs/api.py
- osbs/build/build_requestv2.py
- osbs/build/user_params.py
- osbs/cli/main.py
- osbs/utils.py
- tests/build_/test_user_params.py
> Source container build: allow to use only build_id

- osbs/build/user_params.py
This param is unused in case of source containers.
* OSBS-8040
> user params: source containers: remove filesystem_koji_task_id

- inputs/orchestrator_sources_inner:6.json
because we aren't pulling image anymore
* OSBS-8322
> Source build doesn't need remove_image plugin anymore,

- osbs/cli/main.py
- osbs/core.py
- tests/cli/test_capture.py
- tests/test_core.py
OSBS-8325
Yield a fresh copy (from GET) of the object being watched after successful response from
the watch API, but before streaming data.
> Fix race condition in watch_resource

- docs/configuration_file.md
- osbs/api.py
- osbs/conf.py
- tests/conftest.py
Fixes OSBS-7605
pdc support was deprecated in September 2018, so remove the last remnants
of it from the code.
doc change at https://github.com/containerbuildsystem/osbs-docs/pull/121
> remove obsolete pdc code

- osbs/build/build_requestv2.py
so it can be later used in koji_import to resolve owner
* OSBS-8380
> set koji-task-id label on source container build,

- osbs/http.py
- tests/test_http.py
- tests/test_retries.py
> Use urllib3 directly instead of via requests.packages

- osbs/api.py
- osbs/build/plugins_configuration.py
- osbs/build/user_params.py
- tests/build_/test_plugins_configuration.py
> pass params to download_remote_sources plugin

- inputs/worker_inner:6.json
- tests/build_/test_arrangements.py
> run add_buildargs_in_dockerfile plugin in worker

- osbs/api.py
- osbs/build/build_requestv2.py
- osbs/build/user_params.py
- osbs/repo_utils.py
- osbs/utils.py
- tests/build_/test_arrangements.py
- tests/build_/test_build_requestv2.py
- tests/build_/test_plugins_configuration.py
- tests/build_/test_user_params.py
- tests/test_api.py
user_params: refactor set_params to occur separately of BuildRequest
part of OSBS-8220
Create and populate the BuildUserParams before creating the BuildRequest,
and use the BuildUserParams exclusively as the data store within
BuildRequest.
> user_params: refactor set_params to occur separately of BuildRequest

- osbs/build/build_requestv2.py
- tests/build_/test_build_requestv2.py
> properties in build_request for base_image and triggered_after_koji_task

- inputs/orchestrator_inner:6.json
- inputs/worker_inner:6.json
- osbs/build/plugins_configuration.py
- tests/build_/test_arrangements.py
- tests/build_/test_plugins_configuration.py
Add the add_flatpak_labels plugin, which adds labels from container.yaml
into the generated Dockerfile.
See https://github.com/containerbuildsystem/atomic-reactor/pull/1371
Signed-off-by: Owen W. Taylor <otaylor@fishsoup.net>
> Add the add_flatpak_labels plugin

- osbs/build/plugins_configuration.py
- tests/build_/test_arrangements.py
- tests/build_/test_plugins_configuration.py
Fixes OSBS-3863
koji_promote is being removed from atomic_reactor, so remove the
references to it from osbs-client.
> cleanup: remove references to koji_promote

- osbs/utils.py
- tests/test_utils.py
New label for new type of operators delivery.
* OSBS-8634
> Define label com.redhat.delivery.operator.bundle

- inputs/orchestrator_inner:6.json
- inputs/worker_inner:6.json
- osbs/build/plugins_configuration.py
- tests/build_/test_arrangements.py
- tests/build_/test_plugins_configuration.py
atomic-reactor is being changed to use the 'resolve_composes' plugin
for Flatpaks, instead of having a separate 'resolve_module_compose',
and to add a new 'flatpak_update_dockerfile' plugin that runs after
'resolve_composes'.
The 'resolve_composes' plugin is moved up a bit in the sequence of
orchestrator plugins so that 'flatpak_update_dockerfile' can set the
release label before bump_release runs. As far as I can tell, it should
work as well in the new location as the old location.
See https://github.com/containerbuildsystem/atomic-reactor/pull/1373
> Adjust the pre-build Flatpak plugins

- inputs/orchestrator_inner:6.json
- tests/build_/test_arrangements.py
Plugin will check if user settings are correct.
Nothing prevent this plugin from running on workers but currently
having only orchestrator is fine.
* OSBS-8634
> Run pre_check_user_settings plugin on orchestrator

- osbs/api.py
- tests/test_api.py
Fixes OSBS-8026
Catch when there are an insufficient number of positional arguments to _do_create_prod_build and report which one is missing.
> api: report incomplete positional arguments to _do_create_build

- osbs/build/plugins_configuration.py
- tests/build_/test_plugins_configuration.py
Plugin has to know if build is flatpak build to skip some checks.
* OSBS-8634
> check_user_settings: pass arg if build is flatpak

- osbs-client.spec
- osbs/repo_utils.py
- osbs/schemas/container.json
- requirements.txt
- tests/test_api.py
- tests/test_repo_utils.py
Fixes OSBS-5734
Move the validation of the container.yaml out of atomic-reactor and into osbs-client.
> repo_utils: validate container.yaml against the schema

- inputs/orchestrator_inner:6.json
- inputs/worker_inner:6.json
- osbs/build/plugins_configuration.py
- osbs/build/user_params.py
- tests/build_/test_arrangements.py
- tests/build_/test_plugins_configuration.py
- tests/build_/test_user_params.py
* OSBS-8637
Add BuildUserParams property and PluginsConfiguration render method to
allow orchestrator to pass the 'replacement_pullspecs' param to worker
instances of 'pin_operator_digest'
Add 'pin_operator_digest' to orchestrator and worker inner
configurations
> operators: Add support for pin_operator_digest

- osbs/api.py
- osbs/build/build_requestv2.py
- osbs/build/plugins_configuration.py
- osbs/build/user_params.py
- osbs/conf.py
- tests/build_/test_arrangements.py
- tests/build_/test_build_requestv2.py
- tests/build_/test_plugins_configuration.py
- tests/build_/test_user_params.py
- tests/test_api.py
- tests/test_exceptions.py
Part of OSBS-8220
Fix some minor issues related to #928: build_conf is required for set_params (and some unit tests are restructured accordingly) and only build_from is a valid way to specify the build image or build imagestream.
Requires atomic reactor changes from [PR-1931](https://github.com/containerbuildsystem/atomic-reactor/pull/1391)
> user_params: minor clean-ups after the big refactor

- osbs-client.spec
Fixes: #948 
Read the issue. Thanks
https://copr.fedorainfracloud.org/coprs/martstyk/osbs-client/build/1299777/
It is not necessary to add it under EL7 as with_check is set to 1 only for Fedora  
Signed-off-by: Martin Styk <mastyk@redhat.com>
> spec: add builddep python3-jsonschema

- .packit.yaml
I guess it would be helpful for all contributors to have automated checks for RPM builds. This can mitigate issues like #948 (PR #949).
At the start, I included EL7, EL8, Fedora stable releases + Fedora rawhide. If I'm missing something or something new needs to be added, multiarch for example, just tell me.
You already have approved organization by Packit
Signed-off-by: Martin Styk <mastyk@redhat.com>
> Add support for Packit as a Service

- osbs/schemas/container.json
* OSBS-8637
Add operator_manifest validation to container.yaml
This was already added to atomic-reactor, but container.yaml validation
has since been moved to osbs-client
> operator manifests: Validate user configuration

- osbs/schemas/container.json
Change operator_manifest in container.yaml to operator_manifestS to
unify it with the reactor-config-map option.
> operator manifests: Unify configuration naming

- osbs/utils/labels.py
In cea3df7, we moved the Labels class into its own module. When doing
so, we did not import unicode_literals to the new module. As a
consequence, the keys in the labels dicts became 'str's in python 2.
This patch sets osbs-client back to the former behavior, which is py2/3
consistent.
> Import unicode_literals in labels module

- osbs/schemas/container.json
* OSBS-8639
Add validation for operator_manifest.repo_replacements, where the user
can configure container image repo replacements that are not available
in OSBS site-configuration.
> operator manifests: Validate repo_replacements

- osbs/repo_utils.py
- osbs/utils/yaml.py
- tests/test_repo_utils.py
- tests/utils/test_yaml.py
OSBS-8786
Move read_yaml() and related functions out of repo_utils and into osbs/utils/yaml.py.
Adjust read_yaml() to take a package file which defaults to 'osbs'.
atomic-reactor can now use this version of read_yaml() to read it's own files from its package.
> improve read_yaml between osbs-client and atomic-reactor

- .gitignore
- rel-eng/lib/builder.py
- rel-eng/tito.props
This should fix the problem when tito is not able to create SRPM, due to missing tarball.
> Fix tito builds

- rel-eng/lib/builder.py
Fix all corner cases in Tito.
You can verify this patch as following:
- `tito build --rpm`
- `tito build --rpm --test`
Signed-off-by: Martin Styk <mastyk@redhat.com>
> fix: update tito builder to match with expected value in %setup

- osbs/schemas/container.json
* OSBS-8789
Users can configure whether to enable digest pinning, repo replacements
and registry replacements during operator manifest bundle builds in
container.yaml.
> operator manifests: Validate opt-out options

- osbs/schemas/container.json
ignore_absent_pulp_repos option in container.yaml
* CLOUDBLD-125
> Image owners can make ODCS ignore missing content sets,

- osbs/build/plugins_configuration.py
- osbs/build/user_params.py
- tests/build_/test_plugins_configuration.py
remote_source_configs is a new argument to be passed to the
download_remote_source plugin. It carries information on cachito request
configuration files.
* CLOUDBLD-427
> Pass new param to download_remote_source plugin

- osbs/utils/yaml.py
- tests/utils/test_yaml.py
Atomic-reactor unit-tests depend on osbs-client, this was a breaking change.
We will need to re-do these changes but also make sure they do not break atomic-reactor (or update atomic-reactor tests accordingly).
> Revert jsonschema validation patch

- osbs/build/pod_response.py
- tests/build_/test_pod_response.py
>  Correctly handle `docker-pullable`-prefixed container_image_ids

- osbs/cli/main.py
- Parse arrangement_version as int instead of str
- Update CLI help strings
- CLOUDBLD-153
Signed-off-by: Ben Alkov <ben.alkov@redhat.com>
> Check CLI for arrangements < 6; they are unused

- inputs/orchestrator.json
- inputs/worker.json
- osbs/build/build_requestv2.py
- tests/build_/test_arrangements.py
- tests/build_/test_build_requestv2.py
- tests/constants.py
> Drop ATOMIC_REACTOR_PLUGINS from template

- osbs/schemas/container.json
This is to support forwarding new parameters to Cachito to
support multiple packages in a single source repository.
Relates to CLOUDBLD-1598
Signed-off-by: mprahl <mprahl@users.noreply.github.com>
> Add the "remote_source.packages" key to the JSON schema

- osbs/schemas/container.json
> Build only content sets used just for building content

- test.sh
https://github.com/markdownlint/markdownlint/issues/341
> [markdown] Use older version of mdl (0.9)

- osbs/utils/__init__.py
Usually output of repr() can be used to construct object, it's not
possible currently, because `image` is not an argument in init method.
Also is fun to debug following pytest output:
```
ImageName(image='weird-registry/new-bar@sha256:2') != ImageName(image='weird-registry/new-bar@sha256:2')
```
because in reality it was:
```
ImageName(registry='weird-registry', namespace=None, repo='new-bar',
tag='sha256:2') != ImageName(registry=None, namespace='weird-registry',
repo='new-bar', tag='sha256:2')
```
> Fix ImageName repr()

- requirements-py2.txt
- requirements-py3.txt
- requirements.txt
- setup.py
- test.sh
py2 and py3 diverges we have to keep separated requirement files.
> Separate py2/py3 deps

- osbs/http.py
`.close()` is called from `__del__` and because this happend during
garbage collecting nothing is guaranted [1] and it results into following
traceback printed directly to stderr because it happened in GC context:
```
Traceback (most recent call last):
File "/home/mbasti/repos-upstream/osbs-client/osbs/http.py", line 221, in __del__
self.close()
File "/home/mbasti/repos-upstream/osbs-client/osbs/http.py", line 214, in close
if not self.closed:
AttributeError: 'HttpStream' object has no attribute 'closed'
```
Using getattr instead to avoid traceback.
TLDR: use context managers if you want to be sure that connection is closed
properly.
[1] https://docs.python.org/3/reference/datamodel.html#object.__del__
> HttpStream: fix close method

- .travis.yml
- tests/utils/test_utils.py
* Use latest fedora for testing
* Remove EOL Fedora 30
* Seems that new git/fedora has a time constrains when repo cannot be
instantly used
> Travis: Enable F32 testing

- osbs/schemas/container.json
> skip_all option for operator_manifests in container.yaml

- osbs/api.py
- tests/build_/test_arrangements.py
- tests/test_api.py
If a build is started with the 'flatpak' parameter, but doesn't have a
container.yaml with a 'flatpak' section, or a build is started without
the 'flatpak' parameter, but has a Flatpak container.yaml, the user
would get super-confusing failures, since the repo-parsing part of the code is
independent of the part of the code that checks for build type.
Check for consistency, and throw helpful messages.
Signed-off-by: Owen W. Taylor <otaylor@fishsoup.net>
> api.py: Catch mismatches between the flatpak parameter and the repo

- .github/workflows/linters.yaml
- .github/workflows/unittests.yaml
- .pylintrc
- osbs/build/user_params.py
* CLOUDBLD-3581
Signed-off-by: Chenxiong Qi <cqi@redhat.com>
> Use newer version fedora image in CI

- osbs/api.py
- osbs/build/plugins_configuration.py
- osbs/build/user_params.py
- osbs/cli/main.py
- tests/build_/test_plugins_configuration.py
- tests/test_api.py
Option can pass URL to JSON file with modifications to operator CSV
file.
Can be used only with --isolated option
* CLOUDBLD-3976
- [waived] Pull request has a link to an osbs-docs PR for user documentation updates
> New option --operator-csv-modifications-url

- osbs/api.py
operator_csv_modifications_url option was not passed to user params at
client side
* CLOUDBLD-3976
> Fix: pass operator_csv_modifications_url param to userparams

- inputs/orchestrator_inner:6.json
- tests/build_/test_arrangements.py
This plugin will run on orchestrator to collect maven metadata
from fetch-artifacts-koji and fetch-artifacts-url files
This is an accompanying change for https://github.com/containerbuildsystem/atomic-reactor/pull/1602
Main epic - MMENG-829
Story - MMENG-1275
> add generate_maven_metadata post plugin

- osbs/utils/__init__.py
- tests/utils/test_utils.py
*CLOUDBLD-4640
Signed-off-by: Serhii Salatskyi <ssalatsk@redhat.com>
> User warnings handler requires positional arguments

- osbs/__init__.py
- osbs/cli/main.py
- osbs/constants.py
- osbs/utils/__init__.py
- tests/utils/test_utils.py
> Print user warnings to osbs-client command line output

- .pylintrc
- osbs/api.py
- osbs/cli/main.py
- osbs/conf.py
- osbs/constants.py
- osbs/core.py
- tests/test_api.py
- tests/test_core.py
TODOs should be resolved before merging or issue trackers should be used
instead.
No one ever will go and fix TODOs, mainly if half of them is not valid
because code changes.
- [n/a] Code coverage from testing does not decrease and new code is covered
> No more TODOs and FIXME in code

- osbs/utils/__init__.py
- tests/utils/test_utils.py
*CLOUDBLD-4643
Signed-off-by: Serhii Salatskyi <ssalatsk@redhat.com>
> User warnings can return list of warnings

- osbs/build/plugins_configuration.py
- osbs/build/user_params.py
- tests/build_/test_plugins_configuration.py
> Update user parameters related to remote sources

- osbs/utils/__init__.py
- tests/utils/test_utils.py
*CLOUDBLD-4643
Signed-off-by: Serhii Salatskyi <ssalatsk@redhat.com>
> UserWarningStore returns correct boolean value for PY2 version

- osbs/api.py
- osbs/utils/__init__.py
- tests/utils/test_utils.py
OCP will reject any non-string annotations, make sure values are
converted
> Make sure that annotations are string

- tests/utils/test_utils.py
Popen() doesn't wait until subprocess ends. This causes race-conditions
in git tests. With Popen() .wait() must be called to have deterministic
test.
Fixes: #1028
> Wait for subprocess.Popen()

- tests/utils/test_utils.py
Popen() doesn't wait until subprocess ends. This causes race-conditions
in git tests. With Popen() .wait() must be called to have deterministic
test.
Fixes: #1028
> [ocp3] Wait for subprocess.Popen()

- docs/configuration_file.md
- make_mock_json.py
- osbs/api.py
- osbs/build/plugins_configuration.py
- osbs/build/user_params.py
- osbs/cli/main.py
- osbs/conf.py
- osbs/constants.py
- tests/build_/test_arrangements.py
- tests/build_/test_build_requestv2.py
- tests/build_/test_plugins_configuration.py
- tests/build_/test_user_params.py
- tests/test_api.py
- tests/test_conf.py
Cleanup for tekton
* CLOUDBLD-6299
> Remove all related to arrangement versions

- tests/build_/test_plugins_configuration.py
- tests/test_core.py
- tests/utils/test_utils.py
Context:
- https://github.com/containerbuildsystem/actions/pull/2
> Fix E741 ambiguous variable name 'l'

- osbs/build/user_params.py
Signed-off-by: Ben Alkov <ben.alkov@redhat.com>
> Fix koji_task_id type in user_params docstring

- tests/requirements.txt
- tests/test_api.py
> pin down flexmock 0.11.0 and fix tests

- osbs/exceptions.py
- osbs/utils/__init__.py
- tests/utils/test_utils.py
In OSBS2 we'll reuse the same repo multiple times,
we need to make sure it's not modified locally
before resetting
* CLOUDBLD-7976
> check if the repo ws locally modified before resetting

- osbs/build/plugins_configuration.py
- osbs/build/user_params.py
- osbs/cli/main.py
- tests/build_/test_plugins_configuration.py
- tests/build_/test_user_params.py
- tests/test_api.py
> [OCP3] add userdata cli option and pass userdata to koji_import plugin

- osbs/cli/main.py
- tests/cli/test_main.py
This can be used for automated postprocessing of results
New options --export-metadata-file must be used to enable this behavior
> Allow to export build metada as JSON file

- osbs/cli/main.py
> CLI: Remove --output option

- osbs/tekton.py
- tests/test_api.py
- tests/test_tekton.py
> pipeline run error message about plugins should be same as before

- osbs/api.py
- osbs/cli/main.py
- osbs/tekton.py
- tests/cli/test_main.py
- tests/test_tekton.py
finished reading logs, there is race between all pods finished and
pipeline run changing status
we will wait just for certain amount of time, if pipeline run still
didn't finish by then, there is something really wrong and that will be
already handled
* CLOUDBLD-8359
- n/a] JSON/YAML configuration changes are updated in the relevant schema
> wait_for_finish method, which waits for pipeline run to finish, after we

- osbs/api.py
- osbs/tekton.py
- tests/test_api.py
- tests/test_tekton.py
CLOUDBLD-8889
Add the PipelineRun.pipeline_results property to fetch the raw value of
the .status.pipelineResults field.
Add the OSBS.get_build_results() method to fetch pipeline results and
convert them into a dict with JSON-decoded values.
> Add methods for fetching Tekton results

- osbs/tekton.py
- tests/test_tekton.py
This is to later help separate log by platfrom that is
suffixed in the taskname
* CLOUDBLD-8139
> return logs with the task name that they belong to

- osbs/cli/main.py
- tests/cli/test_main.py
The get_logs(follow=True, wait=True) method was updated to return an
iterator of (task_run_name, log_line) tuples. Fix its usage in the cli
and the mocking in unit tests accordingly.
> Fix printing of logs in cli.main

- osbs/build/user_params.py
- tests/build_/test_user_params.py
- tests/test_api.py
`namespace` can be retrieved from pipeline
context in tekton.
* CLOUDBLD-9054
> don't pass `namespace` in `user_params`

- osbs/api.py
- osbs/build/user_params.py
- tests/test_api.py
It can be fetched from context in tekton
so no need to pass it.
* CLOUDBLD-9053
- n/a Code coverage from testing does not decrease and new code is covered
> don't pass `pipeline_run_name` in `user_params`

- osbs/utils/labels.py
- tests/utils/test_labels.py
CLOUDBLD-8832
OSBS will not provide this label anymore.
> Drop build-host label

- osbs/utils/__init__.py
CLOUDBLD-9971
This will be useful for atomic-reactor, to get the commit ID of the
source repo without having to call clone or reset.
> Provide separate function for getting commit ID

- osbs/api.py
- osbs/tekton.py
- tests/test_api.py
- tests/test_tekton.py
CLOUDBLD-10116
The existing has_succeeded(), was_cancelled() methods only work properly
for finished pipelineRuns (including finally tasks).
Atomic-reactor needs to check the status while the pipeline is still
running, i.e. check the status of non-finally tasks in the finally task.
Add API methods for this purpose.
> Add methods to check failed/cancelled taskRuns

- osbs/tekton.py
- tests/test_tekton.py
> handle missing 'terminated' key for tasksteps in get_error_message

- osbs/tekton.py
- tests/test_api.py
- tests/test_tekton.py
> sort taskRuns in get_logs by startTime, as tasks aren't ordered

- osbs/cli/main.py
- tests/cli/test_main.py
> save entire pipeline info in exported metadata

- osbs/api.py
- tests/test_api.py
CLOUDBLD-10155
This will be used by koji-containerbuild to remove the build right after
it finishes.
> Add api method to remove the build

- osbs/tekton.py
- tests/test_api.py
- tests/test_tekton.py
those which have actual error message set based on task results
* CLOUDBLD-10627
> get_error_message won't show anymore all failed tasks/steps, but only

- osbs/tekton.py
- tests/test_tekton.py
There might be cases where the task runs do not
have the startTime, mostly just if they did not execute
I believe that this is the problem behind CLOUDBLD-10953
> Fix sorting key

- osbs/tekton.py
status, and log what is in status, this shouldn't happen but is sometimes happening
* CLOUDBLD-11209
> when checking task states ignore tasks which don't have conditions in

- osbs/build/user_params.py
- osbs/cli/main.py
- osbs/conf.py
- tests/build_/test_user_params.py
- tests/constants.py
> osbs1 cleanup

- osbs/api.py
- osbs/cli/main.py
- osbs/conf.py
- osbs/repo_utils.py
- osbs/schemas/container.json
- tests/test_api.py
- tests/test_conf.py
> allow user to configure build time for binary pipeline

- osbs/tekton.py
- tests/requirements.txt
- tests/test_api.py
- tests/test_tekton.py
> pipelineResults aren't anymore always json strings

- .github/workflows/unittests.yaml
- docs/configuration_file.md
- osbs/api.py
- osbs/build/user_params.py
- osbs/cli/main.py
- osbs/conf.py
- osbs/constants.py
- osbs/tekton.py
- osbs/utils/otel.py
- requirements.txt
> add `openetelemetry_info` to `user_params`

- osbs/tekton.py
- tests/test_api.py
- tests/test_tekton.py
> new pipelines 1.13 changes

- .github/workflows/linters.yaml
- test.sh
- tests/requirements.txt
See the individual commit messages for details
> Fix the CI issues

- osbs/schemas/container.json
- tests/utils/test_yaml.py
This will allow users to pick version fo remote_sources feature which should be used.
> Add remote_sources_version into container.yaml

- osbs/schemas/container.json
- tests/utils/test_yaml.py
CAchito and cachi2 should support the same set of pkg managers.
Cachi2 allows more pkg managers, but those must be tested and implemented in OSBS as they may interact with existing workflows.
> Limit allowed pkg_managers
